import { createLevel, createModule, createPlaceholderLevel } from "@/lib/course-builders";
import { type LanguageCourseDefinition, type VoiceLessonSeed } from "@/lib/course-types";

const japaneseN5Seeds: VoiceLessonSeed[] = [
  {
    id: "n5-hiragana",
    title: "Hiragana basics",
    objective: "Connect the first common hiragana sounds to live speech instead of isolated memorization.",
    checkpointLabel: "Hiragana sound check",
    supportHint: "Keep reading support minimal and always return to saying the sounds aloud.",
    supportNote: "Use support language only for a one-line distinction if two sounds are mixed.",
    state: "not_started",
    mode: "listening",
    demoPhrase: "ka, ki, ku, ke, ko",
    pattern: "a-row and k-row recognition",
    outcome: "Learner can hear and say beginner kana-linked sounds confidently.",
    replyPrompt: "Repeat the sound row clearly and evenly.",
    acceptableResponses: ["ka ki ku ke ko", "kakikukeko", "かきくけこ"],
    modelPrompt: "Model the a-row and k-row as spoken sounds instead of treating them like flashcards.",
    guidedPrompt: "Ask the learner to repeat, then identify which sound they heard in two quick checks.",
    checkpoint: "Verify the learner can say and recognize the target sounds in sequence.",
  },
  {
    id: "n5-katakana",
    title: "Katakana basics",
    objective: "Prepare the learner for common foreign-sounding words and sharper listening distinctions.",
    checkpointLabel: "Katakana listening check",
    supportHint: "Explain that katakana often appears in imported words, then go right back to speech practice.",
    supportNote: "Use a short native-language note when the learner expects English stress.",
    state: "not_started",
    mode: "listening",
    demoPhrase: "koohii",
    pattern: "simple katakana loanwords",
    outcome: "Learner can repeat and identify beginner loanword pronunciation.",
    replyPrompt: "Repeat the loanword once in Japanese rhythm.",
    acceptableResponses: ["koohii", "kohi", "コーヒー"],
    modelPrompt: "Model two familiar loanwords so the learner hears how Japanese reshapes them.",
    guidedPrompt: "Ask the learner to repeat the words and then answer which version sounded more natural.",
    checkpoint: "Confirm the learner can repeat both loanwords with calmer timing.",
  },
  {
    id: "n5-greetings",
    title: "Essential greetings and politeness",
    objective: "Help the learner sound respectful and comfortable in a first interaction using the most useful Japanese beginner phrases.",
    checkpointLabel: "Greeting confidence check",
    supportHint: "Translate intent, not every word, so the learner stays focused on speaking.",
    supportNote: "If needed, explain when the phrase is used in one short support-language sentence.",
    state: "not_started",
    mode: "roleplay",
    demoPhrase: "ohayou gozaimasu, arigatou gozaimasu",
    pattern: "greetings, thanks, and polite rhythm",
    outcome: "Learner can handle a warm beginner greeting exchange with more trust and less hesitation.",
    replyPrompt: "Say good morning and thank you in one clean phrase.",
    acceptableResponses: [
      "ohayou gozaimasu",
      "arigatou gozaimasu",
      "ohayou gozaimasu arigatou gozaimasu",
      "おはようございます",
      "ありがとうございます",
    ],
    modelPrompt: "Model a natural morning greeting and a polite thank-you so the learner hears cadence, not isolated words.",
    guidedPrompt: "Roleplay a first greeting moment, then ask the learner to answer politely and repeat the phrase with cleaner rhythm.",
    checkpoint: "Finish with one confident greeting line and one thank-you line spoken naturally.",
  },
  {
    id: "n5-introductions",
    title: "Introductions and identity",
    objective: "Teach the learner to say their name, where they are from, and a simple personal detail in clean beginner Japanese.",
    checkpointLabel: "Self-introduction check",
    supportHint: "Explain the sentence pattern once, then move quickly back into voice practice.",
    supportNote: "Keep the coaching practical so the learner focuses on saying the line naturally.",
    state: "not_started",
    mode: "speaking",
    demoPhrase: "hajimemashite, watashi wa Rahul desu",
    pattern: "first introductions and polite self-reference",
    outcome: "Learner can introduce themselves in Japanese without depending on English structure.",
    replyPrompt: "Say hello, give your name, and finish with desu.",
    acceptableResponses: [
      "hajimemashite watashi wa rahul desu",
      "watashi wa rahul desu",
      "はじめまして",
      "わたし は",
      "です",
    ],
    modelPrompt: "Model a very natural first introduction with a calm pace and clear sentence ending.",
    guidedPrompt: "Ask the learner to introduce themselves, then repeat once more with steadier rhythm and cleaner desu.",
    checkpoint: "The learner completes one short self-introduction with confidence and understandable timing.",
  },
  {
    id: "n5-numbers",
    title: "Numbers, time, and counting",
    objective: "Build practical access to numbers so the learner can use Japanese for time, prices, and simple real-life answers.",
    checkpointLabel: "Number fluency check",
    supportHint: "Use support language to explain counting pattern changes only when needed.",
    supportNote: "Keep correction short and go straight into the next spoken prompt.",
    state: "not_started",
    mode: "speaking",
    demoPhrase: "ichi, ni, san, yon, go",
    pattern: "1-10 and simple quantities",
    outcome: "Learner can respond to simple number prompts with less hesitation and more natural pacing.",
    replyPrompt: "Count from one to five, then say three o'clock.",
    acceptableResponses: ["ichi ni san yon go", "sanji", "いち に さん よん ご", "さんじ"],
    modelPrompt: "Model one to ten in two speeds, then place a number inside a simple time expression.",
    guidedPrompt: "Ask the learner for a number, then ask what time it is so they move from repetition into response.",
    checkpoint: "The learner answers a count prompt and one time prompt clearly.",
  },
  {
    id: "n5-everyday-words",
    title: "Everyday words and useful nouns",
    objective: "Give the learner high-frequency words they can immediately use in daily beginner conversation.",
    checkpointLabel: "Useful word recall",
    supportHint: "Support language should only clarify meaning before the learner speaks again.",
    supportNote: "Use meaning support only to unblock speech quickly.",
    state: "not_started",
    mode: "speaking",
    demoPhrase: "mizu, denwa, hon",
    pattern: "objects, places, and daily essentials",
    outcome: "Learner can recognize and say useful daily words instead of staying stuck on abstract drills.",
    replyPrompt: "Say water, phone, and book in Japanese rhythm.",
    acceptableResponses: ["mizu", "denwa", "hon", "みず", "でんわ", "ほん"],
    modelPrompt: "Model three daily words in tiny phrases so the learner hears living Japanese, not list memorization.",
    guidedPrompt: "Ask what the learner has or wants using one short object answer each time.",
    checkpoint: "The learner says three daily words clearly and responds to one simple prompt.",
  },
  {
    id: "n5-questions",
    title: "Simple questions and answers",
    objective: "Move the learner from repeating phrases into answering small questions in live conversation.",
    checkpointLabel: "Question-response check",
    supportHint: "Use support language to explain the answer pattern once, then immediately return to speaking.",
    supportNote: "Keep the learner responding in short lines rather than overthinking grammar.",
    state: "not_started",
    mode: "roleplay",
    demoPhrase: "hai, sou desu / iie, chigaimasu",
    pattern: "yes-no answers and beginner responses",
    outcome: "Learner can answer short prompts and feel the rhythm of conversation starting.",
    replyPrompt: "Answer yes politely, then answer no politely.",
    acceptableResponses: ["hai", "sou desu", "iie", "chigaimasu", "はい", "そうです", "いいえ", "ちがいます"],
    modelPrompt: "Model a simple yes answer and a simple no answer with polite but easy pacing.",
    guidedPrompt: "Ask two tiny questions and have the learner respond once positively and once negatively.",
    checkpoint: "The learner handles one yes answer and one no answer without freezing.",
  },
  {
    id: "n5-sounds",
    title: "Vowels and clean pronunciation",
    objective: "Build comfort with Japanese rhythm, vowels, and clean syllable timing so later phrases sound more natural.",
    checkpointLabel: "Vowel and rhythm check",
    supportHint: "Use the learner's native language to explain mouth shape and rhythm briefly.",
    supportNote: "Explain the vowel shape in the learner's native language only if clarity drops.",
    state: "not_started",
    mode: "repeat",
    demoPhrase: "a, i, u, e, o",
    pattern: "a / i / u / e / o",
    outcome: "Learner can repeat the basic vowel line with stable rhythm and better control.",
    replyPrompt: "Repeat the Japanese vowel line out loud with even timing.",
    acceptableResponses: ["a i u e o", "aiueo", "あいうえお"],
    modelPrompt: "Model the Japanese vowel line slowly, then naturally, so the learner hears timing and openness.",
    guidedPrompt: "Ask the learner to repeat the vowel line and then isolate the hardest vowel once more.",
    checkpoint: "Check whether the learner can say the full vowel line once without stopping.",
  },
  {
    id: "n5-listening",
    title: "Listening recognition and response",
    objective: "Train the ear so the learner can react to short spoken Japanese, not only repeat it.",
    checkpointLabel: "Listening response check",
    supportHint: "Briefly explain what to listen for, then let the learner answer by ear.",
    supportNote: "Give one listening tip only if the learner misses a sound twice.",
    state: "not_started",
    mode: "listening",
    demoPhrase: "arigatou",
    pattern: "beginner listening cues",
    outcome: "Learner can recognize a few familiar phrases and react correctly instead of waiting for text.",
    replyPrompt: "Repeat the phrase you heard, then say what it means in your own words if you can.",
    acceptableResponses: ["arigatou", "ありがとう", "thank you"],
    modelPrompt: "Play a short phrase naturally, then once more with clearer pacing and emotional tone.",
    guidedPrompt: "Ask the learner what they heard, then have them repeat it and confirm the meaning.",
    checkpoint: "The learner identifies the final phrase and responds without a visual hint.",
  },
  {
    id: "n5-checkpoint",
    title: "First real conversation checkpoint",
    objective: "Combine the first N5 speaking habits into one structured checkpoint that feels like a real beginner conversation.",
    checkpointLabel: "Basic 1 readiness",
    supportHint: "Support language should only reassure, not replace the spoken task.",
    supportNote: "Keep encouragement high and corrections minimal so the learner finishes strong.",
    state: "not_started",
    mode: "checkpoint",
    demoPhrase: "hajimemashite, watashi wa Rahul desu",
    pattern: "greetings, sounds, numbers, and common words",
    outcome: "Learner can complete a short guided voice loop that proves they can actually start speaking Japanese.",
    replyPrompt: "Give a short beginner introduction with a greeting, your name, and one polite response.",
    acceptableResponses: [
      "hajimemashite watashi wa rahul desu",
      "はじめまして",
      "わたし は",
      "です",
    ],
    modelPrompt: "Model the full checkpoint once so the learner hears a realistic beginner conversation from start to finish.",
    guidedPrompt: "Run a compact speaking checkpoint that mixes greeting, introduction, numbers, and one listening response.",
    checkpoint: "Mark the module complete after the learner clears the guided conversation with clear effort and stable rhythm.",
  },
];

function createJapaneseN5Modules() {
  return japaneseN5Seeds.map(createModule);
}

export const japaneseCourse: LanguageCourseDefinition = {
  slug: "japanese",
  name: "Japanese",
  nativeSupportLabel: "Native-language support active for beginner correction",
  heroSummary: "Learn Japanese through useful voice-first lessons that begin with greetings, introductions, everyday words, listening, and real beginner conversation.",
  lessonDuration: "15-20 minute voice lesson",
  framework: {
    name: "JLPT",
    levels: [
      createLevel({
        id: "jp-n5",
        officialLabel: "N5",
        productLabel: "Basic 1",
        objective: "Foundational Japanese speaking, listening, and confidence for first live interactions.",
        examTitle: "N5 foundation speaking exam",
        passRequirement: "Clear the guided speaking checkpoint, listening check, and final voice exam.",
        certificateTitle: "Japanese Basic 1 completion certificate",
        certificateSummary: "Issued after the learner passes the N5 foundation voice exam.",
        modules: createJapaneseN5Modules(),
      }),
      createPlaceholderLevel({
        id: "jp-n4",
        officialLabel: "N4",
        productLabel: "Basic 2",
        objective: "Expand everyday communication with longer phrases and more flexible listening.",
      }),
      createPlaceholderLevel({
        id: "jp-n3",
        officialLabel: "N3",
        productLabel: "Intermediate 1",
        objective: "Handle practical real-world conversation with stronger comprehension.",
      }),
      createPlaceholderLevel({
        id: "jp-n2",
        officialLabel: "N2",
        productLabel: "Advanced 1",
        objective: "Build advanced fluency for study, work, and nuanced response control.",
      }),
      createPlaceholderLevel({
        id: "jp-n1",
        officialLabel: "N1",
        productLabel: "Advanced 2",
        objective: "Reach elite-level comprehension and polished spontaneous speaking.",
      }),
    ],
  },
};
