import { createLevel, createModule, createPlaceholderLevel } from "@/lib/course-builders";
import { type LanguageCourseDefinition, type VoiceLessonSeed } from "@/lib/course-types";

const japaneseN5Seeds: VoiceLessonSeed[] = [
  {
    id: "n5-sounds",
    title: "Sounds and pronunciation",
    objective: "Build comfort with Japanese rhythm, vowels, and clean syllable timing before full phrases.",
    checkpointLabel: "Vowel and rhythm check",
    supportHint: "Use the learner's native language to explain mouth shape and rhythm briefly.",
    supportNote: "Explain the vowel shape in the learner's native language only if clarity drops.",
    state: "not_started",
    mode: "repeat",
    demoPhrase: "a, i, u, e, o",
    pattern: "a / i / u / e / o",
    outcome: "Learner can repeat the basic vowel line with stable rhythm.",
    replyPrompt: "Repeat the Japanese vowel line out loud.",
    acceptableResponses: ["a i u e o", "aiueo", "あいうえお"],
    modelPrompt: "Model the Japanese vowel line slowly, then naturally, so the learner hears timing and openness.",
    guidedPrompt: "Ask the learner to repeat the vowel line and then isolate the hardest vowel once more.",
    checkpoint: "Check whether the learner can say the full vowel line once without stopping.",
  },
  {
    id: "n5-hiragana",
    title: "Hiragana basics",
    objective: "Connect the first common hiragana sounds to live speech instead of isolated memorization.",
    checkpointLabel: "Hiragana sound check",
    supportHint: "Keep reading support minimal and always return to saying the sounds aloud.",
    supportNote: "Use support language only for a one-line distinction if two sounds are mixed.",
    state: "not_started",
    mode: "listening",
    demoPhrase: "ka, ki, ku, ke, ko",
    pattern: "a-row and k-row recognition",
    outcome: "Learner can hear and say beginner kana-linked sounds confidently.",
    replyPrompt: "Repeat the sound row clearly and evenly.",
    acceptableResponses: ["ka ki ku ke ko", "kakikukeko", "かきくけこ"],
    modelPrompt: "Model the a-row and k-row as spoken sounds instead of treating them like flashcards.",
    guidedPrompt: "Ask the learner to repeat, then identify which sound they heard in two quick checks.",
    checkpoint: "Verify the learner can say and recognize the target sounds in sequence.",
  },
  {
    id: "n5-katakana",
    title: "Katakana basics",
    objective: "Prepare the learner for common foreign-sounding words and sharper listening distinctions.",
    checkpointLabel: "Katakana listening check",
    supportHint: "Explain that katakana often appears in imported words, then go right back to speech practice.",
    supportNote: "Use a short native-language note when the learner expects English stress.",
    state: "not_started",
    mode: "listening",
    demoPhrase: "koohii",
    pattern: "simple katakana loanwords",
    outcome: "Learner can repeat and identify beginner loanword pronunciation.",
    replyPrompt: "Repeat the loanword once in Japanese rhythm.",
    acceptableResponses: ["koohii", "kohi", "コーヒー"],
    modelPrompt: "Model two familiar loanwords so the learner hears how Japanese reshapes them.",
    guidedPrompt: "Ask the learner to repeat the words and then answer which version sounded more natural.",
    checkpoint: "Confirm the learner can repeat both loanwords with calmer timing.",
  },
  {
    id: "n5-greetings",
    title: "Greetings",
    objective: "Turn beginner phrases into live speaking habits with greetings used naturally in context.",
    checkpointLabel: "Greeting roleplay",
    supportHint: "Translate intent, not every word, so the learner stays focused on speaking.",
    supportNote: "If needed, explain when the phrase is used in one short support-language sentence.",
    state: "not_started",
    mode: "roleplay",
    demoPhrase: "ohayou gozaimasu",
    pattern: "greeting and courtesy phrases",
    outcome: "Learner can answer a simple greeting exchange without freezing.",
    replyPrompt: "Say the greeting back clearly, then add thank you.",
    acceptableResponses: [
      "ohayou gozaimasu",
      "arigatou",
      "ohayou gozaimasu arigatou",
      "おはようございます",
      "ありがとう",
    ],
    modelPrompt: "Model a short greeting exchange with natural pacing and polite tone.",
    guidedPrompt: "Roleplay a first meeting and have the learner answer with one greeting and one courtesy phrase.",
    checkpoint: "Finish with a clean two-line spoken exchange.",
  },
  {
    id: "n5-numbers",
    title: "Numbers and counting",
    objective: "Build fast speaking access to numbers for prices, time, and daily basics.",
    checkpointLabel: "Number fluency check",
    supportHint: "Use support language to explain counting pattern changes only when needed.",
    supportNote: "Keep correction short and go straight into the next spoken prompt.",
    state: "not_started",
    mode: "speaking",
    demoPhrase: "ichi, ni, san, yon, go",
    pattern: "1-10 and simple quantities",
    outcome: "Learner can respond to simple number prompts with less hesitation.",
    replyPrompt: "Count from one to five out loud.",
    acceptableResponses: ["ichi ni san yon go", "いち に さん よん ご"],
    modelPrompt: "Model one to ten in two speeds and call out a few quantities naturally.",
    guidedPrompt: "Ask the learner for a number, then a count of simple objects.",
    checkpoint: "The learner answers three number prompts in a row correctly.",
  },
  {
    id: "n5-nouns",
    title: "Basic nouns and everyday words",
    objective: "Give the learner usable words for self-introduction and simple daily conversation.",
    checkpointLabel: "Everyday word recall",
    supportHint: "Support language should only clarify meaning before the learner speaks again.",
    supportNote: "Use meaning support only to unblock speech quickly.",
    state: "not_started",
    mode: "speaking",
    demoPhrase: "watashi wa Rahul desu",
    pattern: "high-frequency nouns",
    outcome: "Learner can say a few common nouns clearly and recognize them in short prompts.",
    replyPrompt: "Say a simple phrase about yourself using one everyday noun.",
    acceptableResponses: ["watashi wa", "desu", "わたし は", "です"],
    modelPrompt: "Model the words in tiny phrases so the learner hears them in use, not isolation.",
    guidedPrompt: "Ask the learner what they see, have, or like using one-word and short-phrase answers.",
    checkpoint: "Confirm the learner can answer three noun prompts with clean pronunciation.",
  },
  {
    id: "n5-listening",
    title: "Simple listening recognition",
    objective: "Train the ear so the learner can react to short spoken Japanese, not only repeat it.",
    checkpointLabel: "Listening recognition check",
    supportHint: "Briefly explain what to listen for, then let the learner answer by ear.",
    supportNote: "Give one listening tip only if the learner misses a sound twice.",
    state: "not_started",
    mode: "listening",
    demoPhrase: "arigatou",
    pattern: "beginner listening cues",
    outcome: "Learner can recognize a few familiar phrases and respond correctly.",
    replyPrompt: "Repeat the phrase you heard.",
    acceptableResponses: ["arigatou", "ありがとう"],
    modelPrompt: "Play a short phrase naturally, then once more with clearer pacing.",
    guidedPrompt: "Ask the learner what they heard and have them repeat the phrase back once.",
    checkpoint: "The learner identifies and repeats the final phrase correctly.",
  },
  {
    id: "n5-checkpoint",
    title: "Speak-and-repeat checkpoint",
    objective: "Combine the first N5 speaking habits into one structured checkpoint before the level exam.",
    checkpointLabel: "Basic 1 readiness",
    supportHint: "Support language should only reassure, not replace the spoken task.",
    supportNote: "Keep encouragement high and corrections minimal so the learner finishes strong.",
    state: "not_started",
    mode: "checkpoint",
    demoPhrase: "hajimemashite, watashi wa Rahul desu",
    pattern: "greetings, sounds, numbers, and common words",
    outcome: "Learner can complete a short guided voice loop with visible confidence.",
    replyPrompt: "Give a short beginner introduction with one greeting and your name.",
    acceptableResponses: [
      "hajimemashite watashi wa rahul desu",
      "はじめまして",
      "わたし は",
      "です",
    ],
    modelPrompt: "Model the full checkpoint once so the learner hears how the conversation flows.",
    guidedPrompt: "Run a compact speaking checkpoint that mixes greeting, numbers, and recognition prompts.",
    checkpoint: "Mark the module complete after the learner clears the guided checkpoint.",
  },
];

function createJapaneseN5Modules() {
  return japaneseN5Seeds.map(createModule);
}

export const japaneseCourse: LanguageCourseDefinition = {
  slug: "japanese",
  name: "Japanese",
  nativeSupportLabel: "Native-language support active for beginner correction",
  heroSummary: "Learn Japanese through live speech loops that move from sounds to greetings, listening, and checkpoint confidence.",
  lessonDuration: "15-20 minute voice lesson",
  framework: {
    name: "JLPT",
    levels: [
      createLevel({
        id: "jp-n5",
        officialLabel: "N5",
        productLabel: "Basic 1",
        objective: "Foundational Japanese speaking, listening, and confidence for first live interactions.",
        examTitle: "N5 foundation speaking exam",
        passRequirement: "Clear the guided speaking checkpoint, listening check, and final voice exam.",
        certificateTitle: "Japanese Basic 1 completion certificate",
        certificateSummary: "Issued after the learner passes the N5 foundation voice exam.",
        modules: createJapaneseN5Modules(),
      }),
      createPlaceholderLevel({
        id: "jp-n4",
        officialLabel: "N4",
        productLabel: "Basic 2",
        objective: "Expand everyday communication with longer phrases and more flexible listening.",
      }),
      createPlaceholderLevel({
        id: "jp-n3",
        officialLabel: "N3",
        productLabel: "Intermediate 1",
        objective: "Handle practical real-world conversation with stronger comprehension.",
      }),
      createPlaceholderLevel({
        id: "jp-n2",
        officialLabel: "N2",
        productLabel: "Advanced 1",
        objective: "Build advanced fluency for study, work, and nuanced response control.",
      }),
      createPlaceholderLevel({
        id: "jp-n1",
        officialLabel: "N1",
        productLabel: "Advanced 2",
        objective: "Reach elite-level comprehension and polished spontaneous speaking.",
      }),
    ],
  },
};
