export type {
  CompletionState,
  CourseFramework,
  CourseFrameworkName,
  LessonEvaluation,
  CourseLesson,
  CourseLevel,
  ExamQuestion,
  ExamSection,
  KanjiEntry,
  KanjiGroup,
  LanguageCourseResources,
  ModuleExperience,
  CourseModule,
  ModuleReward,
  ResourceLinkSet,
  CourseSlug,
  LanguageCourseDefinition,
  LessonFeedback,
  LessonMode,
  LessonTurn,
  ModuleProgress,
  VocabularyCategory,
  VocabularyEntry,
} from "@/lib/course-types";

export {
  courseSlugs,
  isCourseSlug,
  staticCourseDefinitions as courseDefinitions,
} from "@/lib/course-source";
