import { createJapaneseSeed } from "@/lib/japanese-seed";

export const japaneseN5PhaseZero = [
  createJapaneseSeed({
    id: "n5-japanese-overview",
    title: "What is Japanese?",
    missionTitle: "Mission 1: Enter Japan with a clear map",
    objective: "Introduce Japanese in simple English so the learner knows what the language is and why this journey matters.",
    storyHook: "You have just landed in Tokyo and everything looks mysterious. This first mission explains the map before you start speaking.",
    checkpointLabel: "Japan map check",
    mode: "listening",
    demoPhrase: "nihongo",
    pattern: "course orientation",
    coverage: ["What Japanese is", "Beginner-safe course overview", "Learning promise"],
    outcome: "Learner understands the course promise and feels safe starting from zero.",
    replyPrompt: "Say nihongo clearly once.",
    acceptableResponses: ["nihongo", "にほんご"],
    modelPrompt: "Explain that Japanese will unlock step by step through sound, script, words, and real conversation.",
    guidedPrompt: "Ask the learner what they expect from the course, then have them say nihongo aloud.",
    checkpoint: "Confirm the learner understands this is a full beginner journey.",
    rewardBadge: "First Step in Japan",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-japanese-vs-english",
    title: "How Japanese differs from English",
    missionTitle: "Mission 2: Reset your English habits",
    objective: "Show the learner in English how Japanese differs from English rhythm, script, and sentence feeling.",
    storyHook: "English habits are helpful, but they can also trip you up. This mission helps you reset before practice begins.",
    checkpointLabel: "Difference awareness",
    mode: "listening",
    demoPhrase: "watashi wa Rahul desu",
    pattern: "English versus Japanese rhythm",
    coverage: ["Sentence order awareness", "Rhythm differences", "Why translation is not enough"],
    outcome: "Learner stops expecting Japanese to behave exactly like English.",
    replyPrompt: "Repeat the sample sentence once with calm pacing.",
    acceptableResponses: ["watashi wa rahul desu", "わたしは ラフルです"],
    modelPrompt: "Model one beginner sentence and explain how Japanese sounds more even and less stress-heavy than English.",
    guidedPrompt: "Ask the learner what felt different, then have them repeat the sentence once more.",
    checkpoint: "Learner notices one clear difference between English and Japanese.",
    rewardBadge: "Mindset Reset",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-no-abcd",
    title: "Japanese does not use ABCD",
    missionTitle: "Mission 3: Meet the real Japanese scripts",
    objective: "Teach in English that Japanese does not use the English alphabet as its native writing system.",
    storyHook: "You look for A, B, C, and D on the signs and do not find them. This mission explains what Japan uses instead.",
    checkpointLabel: "Script awareness",
    mode: "listening",
    demoPhrase: "hiragana, katakana, kanji",
    pattern: "script introduction",
    coverage: ["Why ABCD is not the base", "Three writing systems", "Beginner expectation setting"],
    outcome: "Learner understands the three core Japanese writing systems.",
    replyPrompt: "Say hiragana, katakana, and kanji in order.",
    acceptableResponses: ["hiragana katakana kanji", "ひらがな", "カタカナ", "かんじ"],
    modelPrompt: "Introduce hiragana, katakana, and kanji as three friendly doors instead of one overwhelming wall.",
    guidedPrompt: "Ask the learner to repeat the three script names and identify which one feels most new.",
    checkpoint: "Learner can name the three writing systems aloud.",
    rewardBadge: "Script Explorer",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-romaji-intro",
    title: "What is Romaji?",
    missionTitle: "Mission 4: Cross the romaji bridge",
    objective: "Use English teaching to explain romaji as a bridge from familiar letters into Japanese sound.",
    storyHook: "You recognize sushi and arigatou in English letters first. Romaji becomes your first safe bridge into Japanese.",
    checkpointLabel: "Romaji bridge check",
    mode: "repeat",
    demoPhrase: "sushi, arigatou, nihon",
    pattern: "romaji introduction",
    coverage: ["What romaji is", "Why it helps beginners", "Why it is only a bridge"],
    outcome: "Learner can use romaji for support without mistaking it for the final goal.",
    replyPrompt: "Read sushi, arigatou, and nihon aloud in Japanese rhythm.",
    acceptableResponses: ["sushi", "arigatou", "nihon", "すし", "ありがとう", "にほん"],
    modelPrompt: "Model three familiar romaji words and explain that they point toward real Japanese pronunciation.",
    guidedPrompt: "Ask the learner to read the three words and then say which one felt easiest.",
    checkpoint: "Learner completes the romaji bridge with three safe starter words.",
    rewardBadge: "Romaji Bridge Badge",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-romaji-vowels",
    title: "Japanese vowels in Romaji",
    missionTitle: "Mission 5: Hear the five core sounds",
    objective: "Teach aiueo in English through romaji so the learner hears Japanese vowels before script pressure appears.",
    storyHook: "Every future word depends on five vowel sounds. This mission makes them feel friendly before kana arrives.",
    checkpointLabel: "Vowel bridge check",
    mode: "repeat",
    demoPhrase: "a, i, u, e, o",
    pattern: "aiueo",
    coverage: ["a i u e o", "English comparison hints", "Mouth shape and timing"],
    outcome: "Learner can repeat aiueo with steady beginner confidence.",
    replyPrompt: "Say a, i, u, e, o once with even rhythm.",
    acceptableResponses: ["a i u e o", "aiueo", "あいうえお"],
    modelPrompt: "Model aiueo slowly and then naturally so the learner hears clean Japanese vowel timing.",
    guidedPrompt: "Ask the learner to repeat the full line, then retry the hardest vowel.",
    checkpoint: "Learner can say aiueo without stopping.",
    rewardBadge: "Vowel Master",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-mini-vowel-words",
    title: "Mini vowel words",
    missionTitle: "Mission 6: Turn vowels into tiny words",
    objective: "Move from isolated vowels into tiny beginner words that make sound practice feel useful.",
    storyHook: "You start hearing Japanese not as abstract sounds but as real words like ie and ue.",
    checkpointLabel: "Mini word check",
    mode: "speaking",
    demoPhrase: "ai, ie, ue",
    pattern: "vowel-based words",
    coverage: ["あい", "いえ", "うえ", "Early word rhythm"],
    outcome: "Learner can connect vowels to tiny spoken words.",
    replyPrompt: "Say ai, ie, and ue clearly once.",
    acceptableResponses: ["ai ie ue", "あい", "いえ", "うえ"],
    modelPrompt: "Model tiny beginner words so the learner feels the jump from pure sound into meaning.",
    guidedPrompt: "Ask the learner to repeat the words and identify which one means house.",
    checkpoint: "Learner completes the first tiny-word mission.",
    rewardBadge: "First Sound Badge",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-k-row",
    title: "K-row sounds",
    missionTitle: "Mission 7: Unlock the ka-row",
    objective: "Teach the first consonant-plus-vowel row so Japanese sound structure becomes visible.",
    storyHook: "This is the moment Japanese starts behaving like a system. The ka-row opens the first real row pattern.",
    checkpointLabel: "K-row check",
    mode: "repeat",
    demoPhrase: "ka ki ku ke ko",
    pattern: "k-row practice",
    coverage: ["ka ki ku ke ko", "Row rhythm", "Kana sound expectation"],
    outcome: "Learner can say the full ka-row clearly.",
    replyPrompt: "Say ka ki ku ke ko once in order.",
    acceptableResponses: ["ka ki ku ke ko", "かきくけこ"],
    modelPrompt: "Model the ka-row like a calm rhythm drill, not a textbook chant.",
    guidedPrompt: "Ask the learner to repeat the full row and then isolate ko for one cleaner retry.",
    checkpoint: "Learner says the full ka-row in one pass.",
    rewardBadge: "K-Row Starter",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-s-row",
    title: "S-row sounds",
    missionTitle: "Mission 8: Unlock the sa-row",
    objective: "Teach the sa-row and its special shi sound in clear English support.",
    storyHook: "The sa-row adds the first beginner irregularity, and that makes it an important listening mission.",
    checkpointLabel: "S-row check",
    mode: "repeat",
    demoPhrase: "sa shi su se so",
    pattern: "s-row practice",
    coverage: ["sa shi su se so", "Special shi sound", "Contrast with English sh"],
    outcome: "Learner can hear and repeat the sa-row accurately.",
    replyPrompt: "Say sa shi su se so clearly in order.",
    acceptableResponses: ["sa shi su se so", "さしすせそ"],
    modelPrompt: "Model the sa-row with special attention to shi so the learner hears the contrast immediately.",
    guidedPrompt: "Ask the learner to repeat the row and retry shi once with smoother timing.",
    checkpoint: "Learner completes the sa-row with a clean shi.",
    rewardBadge: "S-Row Starter",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-t-row",
    title: "T-row sounds",
    missionTitle: "Mission 9: Unlock the ta-row",
    objective: "Teach ta, chi, tsu, te, and to in a beginner-safe voice loop.",
    storyHook: "The ta-row introduces more Japanese sound personality. This mission makes chi and tsu less intimidating.",
    checkpointLabel: "T-row check",
    mode: "repeat",
    demoPhrase: "ta chi tsu te to",
    pattern: "t-row practice",
    coverage: ["ta chi tsu te to", "chi and tsu contrast", "Breath control"],
    outcome: "Learner can repeat the full ta-row with more confidence.",
    replyPrompt: "Say ta chi tsu te to once in order.",
    acceptableResponses: ["ta chi tsu te to", "たちつてと"],
    modelPrompt: "Model chi and tsu carefully so the learner hears them as manageable sounds, not traps.",
    guidedPrompt: "Ask the learner for the full row and then repeat tsu once slowly.",
    checkpoint: "Learner completes the ta-row without freezing on chi or tsu.",
    rewardBadge: "T-Row Starter",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-n-h-rows",
    title: "N and H rows",
    missionTitle: "Mission 10: Expand your beginner sound map",
    objective: "Add the n-row and h-row so the learner starts hearing larger patterns across Japanese.",
    storyHook: "With more rows unlocked, Japanese starts feeling like a living sound grid instead of a mystery.",
    checkpointLabel: "N and H row check",
    mode: "speaking",
    demoPhrase: "na ni nu ne no, ha hi fu he ho",
    pattern: "n-row and h-row",
    coverage: ["na-row", "ha-row", "Special fu sound", "Comparing rows"],
    outcome: "Learner can speak two rows and notice how fu differs from English expectations.",
    replyPrompt: "Say the na-row, then the ha-row with special care on fu.",
    acceptableResponses: ["na ni nu ne no", "ha hi fu he ho", "なにぬねの", "はひふへほ"],
    modelPrompt: "Model the two rows clearly and explain fu in one short English note before returning to speech.",
    guidedPrompt: "Ask the learner for both rows and one cleaner retry of fu.",
    checkpoint: "Learner completes two rows with a usable fu sound.",
    rewardBadge: "Row Builder",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-m-y-r-w-rows",
    title: "M, Y, R, and W rows",
    missionTitle: "Mission 11: Finish the core sound map",
    objective: "Complete the main beginner sound rows so the learner can prepare for kana with stronger rhythm awareness.",
    storyHook: "This mission closes the loop on the core Japanese sound map and prepares you for script mastery.",
    checkpointLabel: "Core sound map complete",
    mode: "speaking",
    demoPhrase: "ma mi mu me mo, ya yu yo, ra ri ru re ro, wa wo n",
    pattern: "final core rows",
    coverage: ["ma-row", "ya yu yo", "ra-row", "wa wo n", "Whole sound map review"],
    outcome: "Learner can move through the final core rows with more comfort and momentum.",
    replyPrompt: "Say the ma-row, the ya-yu-yo set, the ra-row, and wa-wo-n.",
    acceptableResponses: ["ma mi mu me mo", "ya yu yo", "ra ri ru re ro", "wa wo n", "まみむめも"],
    modelPrompt: "Model the remaining rows like a complete beginner sound map ready for kana practice.",
    guidedPrompt: "Ask the learner to move through each group and then repeat the ra-row once more.",
    checkpoint: "Learner finishes the full pre-kana sound map.",
    rewardBadge: "Sound Map Complete",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-romaji-to-hiragana",
    title: "Moving from Romaji to Hiragana",
    missionTitle: "Mission 12: Leave the bridge behind",
    objective: "Prepare the learner to shift from romaji support into true hiragana reading.",
    storyHook: "The bridge has done its job. Now you start stepping onto real Japanese script without losing confidence.",
    checkpointLabel: "Romaji exit check",
    mode: "listening",
    demoPhrase: "すし, ねこ, にほん",
    pattern: "romaji to hiragana transition",
    coverage: ["Romaji fade-out", "First hiragana targets", "Confidence shift into script"],
    outcome: "Learner feels ready to enter the hiragana section without panic.",
    replyPrompt: "Read sushi, neko, and nihon using the script if you can.",
    acceptableResponses: ["sushi", "neko", "nihon", "すし", "ねこ", "にほん"],
    modelPrompt: "Model the same word first in romaji, then in hiragana, and explain the shift in one simple English line.",
    guidedPrompt: "Ask the learner to read the three words and notice how much less they need the romaji now.",
    checkpoint: "Learner is ready to begin true hiragana lessons.",
    rewardBadge: "Bridge Complete",
    rewardXp: 15,
  }),
];
