import { type SupplementalVocabularyBank } from "@/lib/japanese-vocab-supplement";

export const japaneseVocabularyExtraF: SupplementalVocabularyBank = {
  "shopping-words": [
    ["これ", "kore", "this"],
    ["それ", "sore", "that near you"],
    ["あれ", "are", "that over there"],
    ["どれ", "dore", "which one"],
    ["こちら", "kochira", "this way or this one politely"],
    ["そちら", "sochira", "that way or that one politely"],
    ["あちら", "achira", "that way over there politely"],
    ["どちら", "dochira", "which way or which one politely"],
    ["みせます", "misemasu", "to show"],
    ["ためします", "tameshimasu", "to try"],
    ["えらびます", "erabimasu", "to choose"],
    ["かわいい", "kawaii", "cute"],
    ["きれい", "kirei", "pretty or clean"],
    ["サイズがありますか", "saizu ga arimasu ka", "do you have this size"],
    ["ほかのいろ", "hoka no iro", "another color"],
    ["うりば", "uriba", "sales floor"],
    ["おすすめ", "osusume", "recommendation"],
    ["にんき", "ninki", "popular"],
  ],
  "direction-words": [
    ["まっすぐ", "massugu", "straight ahead"],
    ["ひだり", "hidari", "left"],
    ["みぎ", "migi", "right"],
    ["うえ", "ue", "up"],
    ["した", "shita", "down"],
    ["まえ", "mae", "front"],
    ["うしろ", "ushiro", "behind"],
    ["なか", "naka", "inside"],
    ["そと", "soto", "outside"],
    ["きた", "kita", "north"],
    ["みなみ", "minami", "south"],
    ["ひがし", "higashi", "east"],
    ["にし", "nishi", "west"],
    ["となり", "tonari", "next to"],
    ["ちかく", "chikaku", "near"],
    ["とおい", "tooi", "far"],
    ["むこう", "mukou", "the other side"],
    ["あいだ", "aida", "between"],
  ],
  "school-words": [
    ["がっこう", "gakkou", "school"],
    ["きょうしつ", "kyoushitsu", "classroom"],
    ["せき", "seki", "seat"],
    ["くろいた", "kuroita", "blackboard"],
    ["じゅぎょう", "jugyou", "class lesson"],
    ["やすみじかん", "yasumi jikan", "break time"],
    ["しけん", "shiken", "exam"],
    ["てんすう", "tensuu", "score"],
    ["せいせき", "seiseki", "grade"],
    ["そつぎょう", "sotsugyou", "graduation"],
    ["にゅうがく", "nyuugaku", "school entrance"],
    ["たいくかん", "taikukan", "gymnasium"],
    ["うんどうじょう", "undoujou", "school field"],
    ["ぶかつ", "bukatsu", "club activity"],
    ["がくぶ", "gakubu", "faculty"],
    ["せんもん", "senmon", "specialty"],
    ["がくねん", "gakunen", "school year"],
    ["ともだち", "tomodachi", "friend"],
  ],
  "house-words": [
    ["へや", "heya", "room"],
    ["だいどころ", "daidokoro", "kitchen"],
    ["おふろ", "ofuro", "bath"],
    ["げんかん", "genkan", "entryway"],
    ["いま", "ima", "living room"],
    ["まど", "mado", "window"],
    ["ドア", "doa", "door"],
    ["ゆか", "yuka", "floor"],
    ["てんじょう", "tenjou", "ceiling"],
    ["ベッド", "beddo", "bed"],
    ["ふとん", "futon", "futon bedding"],
    ["でんき", "denki", "light or electricity"],
    ["エアコン", "eakon", "air conditioner"],
    ["せんたくき", "sentakuki", "washing machine"],
    ["そうじします", "souji shimasu", "to clean"],
    ["せんたくします", "sentaku shimasu", "to do laundry"],
    ["りょうしんのいえ", "ryoushin no ie", "parents' house"],
    ["ひっこします", "hikkoshimasu", "to move house"],
  ],
};
