import { type SupplementalVocabularyBank } from "@/lib/japanese-vocab-supplement";

export const japaneseVocabularyExtraC: SupplementalVocabularyBank = {
  countries: [
    ["にほん", "nihon", "Japan"],
    ["ちゅうごく", "chuugoku", "China"],
    ["かんこく", "kankoku", "Korea"],
    ["イギリス", "igirisu", "United Kingdom"],
    ["フランス", "furansu", "France"],
    ["ドイツ", "doitsu", "Germany"],
    ["スペイン", "supein", "Spain"],
    ["イタリア", "itaria", "Italy"],
    ["オーストラリア", "oosutoraria", "Australia"],
    ["カナダ", "kanada", "Canada"],
    ["ブラジル", "burajiru", "Brazil"],
    ["タイ", "tai", "Thailand"],
    ["ベトナム", "betonamu", "Vietnam"],
    ["インドネシア", "indoneshia", "Indonesia"],
    ["フィリピン", "firipin", "Philippines"],
    ["ロシア", "roshia", "Russia"],
    ["メキシコ", "mekishiko", "Mexico"],
    ["ネパール", "nepaaru", "Nepal"],
  ],
  languages: [
    ["にほんご", "nihongo", "Japanese language"],
    ["えいご", "eigo", "English language"],
    ["ちゅうごくご", "chuugokugo", "Chinese language"],
    ["かんこくご", "kankokugo", "Korean language"],
    ["フランスご", "furansugo", "French language"],
    ["ドイツご", "doitsugo", "German language"],
    ["スペインご", "supeingo", "Spanish language"],
    ["ヒンディーご", "hindii go", "Hindi language"],
    ["ことば", "kotoba", "word or language"],
    ["はつおん", "hatsuon", "pronunciation"],
    ["いみ", "imi", "meaning"],
    ["ぶんぽう", "bunpou", "grammar"],
    ["かんじ", "kanji", "Chinese characters"],
    ["ひらがな", "hiragana", "hiragana"],
    ["カタカナ", "katakana", "katakana"],
    ["かいわ", "kaiwa", "conversation"],
    ["ほんやく", "hon'yaku", "translation"],
    ["つうやく", "tsuuyaku", "interpretation"],
  ],
  food: [
    ["たまご", "tamago", "egg"],
    ["くだもの", "kudamono", "fruit"],
    ["りんご", "ringo", "apple"],
    ["みかん", "mikan", "mandarin orange"],
    ["バナナ", "banana", "banana"],
    ["ごはんもの", "gohan mono", "rice dish"],
    ["カレー", "karee", "curry"],
    ["ぎゅうにく", "gyuuniku", "beef"],
    ["とりにく", "toriniku", "chicken"],
    ["ぶたにく", "butaniku", "pork"],
    ["さかなりょうり", "sakana ryouri", "fish dish"],
    ["サラダ", "sarada", "salad"],
    ["スープ", "suupu", "soup"],
    ["ケーキ", "keeki", "cake"],
    ["アイスクリーム", "aisukuriimu", "ice cream"],
    ["あさごはん", "asagohan", "breakfast"],
    ["ひるごはん", "hirugohan", "lunch"],
    ["ばんごはん", "bangohan", "dinner"],
  ],
  drinks: [
    ["ぎゅうにゅう", "gyuunyuu", "milk"],
    ["ジュース", "juusu", "juice"],
    ["ビール", "biiru", "beer"],
    ["ワイン", "wain", "wine"],
    ["おさけ", "osake", "alcohol or sake"],
    ["みそしる", "misoshiru", "miso soup"],
    ["みずいろののみもの", "mizuiro no nomimono", "blue drink"],
    ["つめたいみず", "tsumetai mizu", "cold water"],
    ["あたたかいおちゃ", "atatakai ocha", "hot tea"],
    ["ココア", "kokoa", "cocoa"],
    ["こうちゃ", "koucha", "black tea"],
    ["りょくちゃ", "ryokucha", "green tea"],
    ["ウーロンちゃ", "uuron cha", "oolong tea"],
    ["のみもの", "nomimono", "drink"],
    ["いっぱい", "ippai", "one cup"],
    ["おかわり", "okawari", "refill"],
    ["のどがかわきました", "nodo ga kawakimashita", "I am thirsty"],
    ["カフェラテ", "kaferate", "cafe latte"],
  ],
  places: [
    ["まち", "machi", "town"],
    ["むら", "mura", "village"],
    ["こうえん", "kouen", "park"],
    ["うみ", "umi", "sea"],
    ["かわべ", "kawabe", "riverside"],
    ["みなと", "minato", "port"],
    ["みち", "michi", "road"],
    ["まどぐち", "madoguchi", "counter window"],
    ["にしぐち", "nishiguchi", "west exit"],
    ["ひがしぐち", "higashiguchi", "east exit"],
    ["いりぐち", "iriguchi", "entrance"],
    ["でぐち", "deguchi", "exit"],
    ["ちかく", "chikaku", "nearby"],
    ["とおく", "tooku", "far away"],
    ["まんなか", "mannaka", "center"],
    ["となり", "tonari", "next to"],
    ["そば", "soba", "beside"],
    ["ばしょ", "basho", "place"],
  ],
};
