import { createJapaneseSeed } from "@/lib/japanese-seed";

export const japaneseN5PhaseKatakana = [
  createJapaneseSeed({
    id: "n5-katakana-overview",
    title: "What is Katakana?",
    missionTitle: "Mission 23: Enter the world of Japanese modern words",
    objective: "Explain in English what katakana is used for and why it matters in travel, food, names, and technology.",
    storyHook: "From airports to coffee shops, katakana is everywhere in modern Japan. This mission opens that door.",
    checkpointLabel: "Katakana overview",
    mode: "listening",
    demoPhrase: "ホテル, バス, コーヒー",
    pattern: "katakana purpose",
    coverage: ["Foreign words", "Names", "Country words", "Technology and food vocabulary"],
    outcome: "Learner understands why katakana matters before learning the chart.",
    replyPrompt: "Say hotel, bus, and coffee in Japanese rhythm.",
    acceptableResponses: ["ホテル", "バス", "コーヒー", "hoteru", "basu", "koohii"],
    modelPrompt: "Introduce katakana as the script of modern and imported vocabulary the learner will hear often.",
    guidedPrompt: "Ask the learner to repeat the three sample words and notice the Japanese rhythm inside them.",
    checkpoint: "Learner understands why katakana appears in daily Japanese life.",
    rewardBadge: "Katakana Explorer",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-katakana-a-k",
    title: "Katakana a and k rows",
    missionTitle: "Mission 24: Read your first katakana rows",
    objective: "Teach アイウエオ and カキクケコ with sound-first support so the learner sees katakana as familiar, not alien.",
    storyHook: "The shapes look sharper than hiragana, but the sounds are already inside you. This mission proves that fast.",
    checkpointLabel: "Katakana row check",
    mode: "listening",
    demoPhrase: "ア イ ウ エ オ, カ キ ク ケ コ",
    pattern: "katakana first rows",
    coverage: ["アイウエオ", "カキクケコ", "Sound continuity from hiragana"],
    outcome: "Learner can read the first katakana rows with confidence.",
    replyPrompt: "Read the a-row and k-row in katakana.",
    acceptableResponses: ["アイウエオ", "カキクケコ", "a i u e o", "ka ki ku ke ko"],
    modelPrompt: "Model the rows as familiar sounds in new shapes so the learner feels continuity rather than fear.",
    guidedPrompt: "Ask the learner to read both rows and say which shape group felt easier.",
    checkpoint: "Learner completes the first katakana rows.",
    rewardBadge: "Katakana Starter",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-katakana-s-t",
    title: "Katakana s and t rows",
    missionTitle: "Mission 25: Read more katakana with special sounds",
    objective: "Teach サシスセソ and タチツテト with beginner support for シ and ツ contrast.",
    storyHook: "Katakana can be visually tricky, so this mission slows down just enough to make the patterns feel reliable.",
    checkpointLabel: "Katakana contrast check",
    mode: "listening",
    demoPhrase: "サ シ ス セ ソ, タ チ ツ テ ト",
    pattern: "katakana contrast rows",
    coverage: ["サ-row", "タ-row", "シ vs ツ awareness", "Reading stability"],
    outcome: "Learner reads these katakana rows with better visual and sound control.",
    replyPrompt: "Read the s-row and t-row in katakana.",
    acceptableResponses: ["サシスセソ", "タチツテト", "sa shi su se so"],
    modelPrompt: "Model the rows and call attention to シ and ツ in one short English clarification.",
    guidedPrompt: "Ask the learner to read both rows and retry one difficult pair once more.",
    checkpoint: "Learner finishes the katakana contrast mission.",
    rewardBadge: "Katakana Contrast",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-katakana-remaining-rows",
    title: "Remaining katakana rows",
    missionTitle: "Mission 26: Complete the basic katakana chart",
    objective: "Finish the remaining basic katakana rows so the learner owns the full 46-character system.",
    storyHook: "This mission closes the basic katakana chart and prepares you for real travel and food words.",
    checkpointLabel: "Full katakana chart ready",
    mode: "speaking",
    demoPhrase: "ナ ニ ヌ ネ ノ, ハ ヒ フ ヘ ホ, マ ミ ム メ モ, ヤ ユ ヨ, ラ リ ル レ ロ, ワ ヲ ン",
    pattern: "full katakana chart",
    coverage: ["Remaining rows", "ン", "Full 46-character chart"],
    outcome: "Learner can move through the rest of the katakana chart with real beginner confidence.",
    replyPrompt: "Read the remaining katakana groups out loud.",
    acceptableResponses: ["ナニヌネノ", "ハヒフヘホ", "ラリルレロ", "ワヲン"],
    modelPrompt: "Model the remaining rows as the completion of a full beginner script map.",
    guidedPrompt: "Ask the learner for two full rows and one final-symbol group to close the chart.",
    checkpoint: "Learner completes the full basic katakana chart.",
    rewardBadge: "Katakana Chart Complete",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-katakana-loanwords",
    title: "Starter katakana words",
    missionTitle: "Mission 27: Read travel and cafe words",
    objective: "Teach common katakana words like hotel, bus, coffee, and taxi through friendly reading practice.",
    storyHook: "Now the script starts paying off. You can read words you might actually hear on your first day in Japan.",
    checkpointLabel: "Katakana word mission",
    mode: "speaking",
    demoPhrase: "ホテル, バス, タクシー, コーヒー",
    pattern: "travel and cafe katakana",
    coverage: ["Travel words", "Cafe words", "Common imported vocabulary"],
    outcome: "Learner can read useful katakana words instead of empty symbols.",
    replyPrompt: "Read hotel, bus, taxi, and coffee aloud in Japanese.",
    acceptableResponses: ["ホテル", "バス", "タクシー", "コーヒー", "hoteru", "takushii"],
    modelPrompt: "Model travel and cafe words with natural Japanese rhythm so the learner hears them as living vocabulary.",
    guidedPrompt: "Ask the learner to read four practical words and identify which one means coffee.",
    checkpoint: "Learner completes the first useful katakana word set.",
    rewardBadge: "Loanword Reader",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-katakana-names-countries",
    title: "Names and country words",
    missionTitle: "Mission 28: Read names from the wider world",
    objective: "Teach country names and foreign-name style katakana so the learner hears how Japan adapts global words.",
    storyHook: "India, America, and your own name sound different in Japanese. This mission makes that fun instead of strange.",
    checkpointLabel: "Name and country check",
    mode: "speaking",
    demoPhrase: "インド, アメリカ, ラフル",
    pattern: "countries and names",
    coverage: ["Country names", "Foreign names", "Identity in katakana"],
    outcome: "Learner can say a few country and name words in Japanese katakana rhythm.",
    replyPrompt: "Say India, America, and Rahul in Japanese.",
    acceptableResponses: ["インド", "アメリカ", "ラフル", "indo", "amerika", "rahuru"],
    modelPrompt: "Model country and name words so the learner hears how Japanese reshapes global sounds.",
    guidedPrompt: "Ask the learner to repeat the three words and notice how their own name changes in Japanese rhythm.",
    checkpoint: "Learner completes the name and country mission.",
    rewardBadge: "Global Katakana",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-katakana-dakuon",
    title: "Katakana dakuon and handakuon",
    missionTitle: "Mission 29: Add voiced modern sounds",
    objective: "Teach ガ-row and パ-row style katakana sounds so modern vocabulary becomes clearer.",
    storyHook: "Baggu and beddo do not work without voiced sounds. This mission brings modern Japanese pronunciation alive.",
    checkpointLabel: "Voiced katakana check",
    mode: "repeat",
    demoPhrase: "ガ ギ グ ゲ ゴ, パ ピ プ ペ ポ",
    pattern: "voiced katakana",
    coverage: ["ガ-row", "ザ-row", "ダ-row", "バ-row", "パ-row"],
    outcome: "Learner can repeat voiced katakana rows more accurately.",
    replyPrompt: "Repeat one voiced row and the pa-row clearly.",
    acceptableResponses: ["ガギグゲゴ", "パピプペポ", "ga gi gu ge go", "pa pi pu pe po"],
    modelPrompt: "Model the voiced and pa sounds through practical words like baggu and pan.",
    guidedPrompt: "Ask the learner to repeat a voiced row and the pa-row once each.",
    checkpoint: "Learner clears voiced katakana practice.",
    rewardBadge: "Modern Sound Badge",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-katakana-yoon-long",
    title: "Katakana yoon and long vowels",
    missionTitle: "Mission 30: Handle long modern word shapes",
    objective: "Teach combinations and long vowels in katakana so the learner can speak words like ジュース and チョコレート more naturally.",
    storyHook: "Modern words stretch, glide, and pause differently. This mission helps your ear catch that music.",
    checkpointLabel: "Katakana long-sound check",
    mode: "repeat",
    demoPhrase: "ジュース, シャツ, チョコレート",
    pattern: "long vowels and combinations",
    coverage: ["ジュ", "シャ", "チョ", "Long vowel mark ー", "Modern word flow"],
    outcome: "Learner can repeat longer katakana words with stronger timing and clarity.",
    replyPrompt: "Repeat juice, shirt, and chocolate in Japanese rhythm.",
    acceptableResponses: ["ジュース", "シャツ", "チョコレート", "juusu", "shatsu", "chokoreeto"],
    modelPrompt: "Model the long-vowel mark and yoon combinations through familiar modern items.",
    guidedPrompt: "Ask the learner to repeat the three words and retry the longest one once more.",
    checkpoint: "Learner completes the long-sound katakana mission.",
    rewardBadge: "Long Sound Explorer",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-katakana-review",
    title: "Full katakana practice",
    missionTitle: "Mission 31: Lock in your katakana reading",
    objective: "Review the full katakana chart and useful words so the learner feels stable before moving on.",
    storyHook: "This is your katakana consolidation mission, where modern Japanese words start to feel readable instead of decorative.",
    checkpointLabel: "Katakana mastery check",
    mode: "checkpoint",
    demoPhrase: "アイウエオ, カキクケコ, ホテル, コーヒー",
    pattern: "full katakana review",
    coverage: ["Full chart review", "Common words", "Voiced sounds", "Long vowels"],
    outcome: "Learner leaves katakana with genuine reading confidence.",
    replyPrompt: "Read one row and two useful katakana words aloud.",
    acceptableResponses: ["アイウエオ", "カキクケコ", "ホテル", "コーヒー"],
    modelPrompt: "Model a compact but satisfying katakana review that feels like a real achievement.",
    guidedPrompt: "Ask the learner to read one row, one travel word, and one cafe word to finish the section.",
    checkpoint: "Learner is ready to use katakana inside broader N5 Japanese.",
    rewardBadge: "Katakana Explorer",
    rewardXp: 20,
  }),
];
