import { createJapaneseSeed } from "@/lib/japanese-seed";

export const japaneseN5Language = [
  createJapaneseSeed({
    id: "n5-first-100-words",
    title: "First 100 words",
    missionTitle: "Mission 11: Build your first useful Japanese word bank",
    objective: "Build a living beginner vocabulary through people, food, places, and objects the learner can actually use.",
    storyHook: "Instead of memorizing a dead list, you start collecting words you can use in cafés, homes, stations, and conversations.",
    checkpointLabel: "First words badge check",
    mode: "speaking",
    demoPhrase: "mizu, hon, eki, tomodachi",
    pattern: "high-frequency beginner vocabulary",
    coverage: ["People", "Family", "Food and drink", "Places", "Objects", "Weather"],
    outcome: "Learner can say useful N5 words instead of feeling trapped in theory.",
    replyPrompt: "Say water, book, station, and friend in Japanese.",
    rewardBadge: "First Words Badge",
    rewardXp: 20,
    acceptableResponses: ["mizu", "hon", "eki", "tomodachi", "みず", "ほん", "えき", "ともだち"],
    modelPrompt: "Model beginner words inside tiny real-life chunks so meaning and pronunciation land together.",
    guidedPrompt: "Ask the learner what they want, where they are, and who they are with using short word answers.",
    checkpoint: "The learner recalls and says four useful beginner words clearly.",
  }),
  createJapaneseSeed({
    id: "n5-vocabulary-bank",
    title: "Vocabulary bank in context",
    missionTitle: "Mission 12: Turn vocabulary into living phrases",
    objective: "Turn the growing N5 vocabulary list into a usable bank of travel, food, school, and daily-life language.",
    storyHook: "Words become powerful only when they appear inside real phrases. This mission moves your vocabulary from flashcards into speech.",
    checkpointLabel: "Context vocabulary check",
    mode: "listening",
    demoPhrase: "みずをください。 コーヒーをのみます。",
    pattern: "vocabulary inside phrases",
    coverage: ["Phrase-level vocabulary", "Travel words", "Food and drink use", "School words", "Daily expressions", "Toward the 800-word bank"],
    outcome: "Learner hears words in context and stops treating vocabulary like a disconnected list.",
    replyPrompt: "Repeat the phrase for water please, then the phrase for drinking coffee.",
    rewardBadge: "Context Builder",
    rewardXp: 20,
    acceptableResponses: ["mizu o kudasai", "koohii o nomimasu", "みずをください", "コーヒーをのみます"],
    modelPrompt: "Model simple phrase-level vocabulary so each word arrives with action and purpose.",
    guidedPrompt: "Ask the learner to repeat a useful phrase, then swap one noun so they stay active.",
    checkpoint: "The learner uses vocabulary inside two short spoken phrases.",
  }),
  createJapaneseSeed({
    id: "n5-greetings",
    title: "Greetings",
    missionTitle: "Mission 13: Sound warm and polite immediately",
    objective: "Teach the beginner greetings that instantly make the learner sound warm, polite, and human.",
    storyHook: "The fastest way to feel welcomed in Japan is to greet well. This mission gives you the phrases people actually hear every day.",
    checkpointLabel: "Greeting confidence check",
    mode: "roleplay",
    demoPhrase: "ohayou gozaimasu, konnichiwa, arigatou gozaimasu",
    pattern: "greetings and politeness",
    coverage: ["Morning, day, evening greetings", "Thank you", "Sorry and excuse me", "Please", "Polite tone"],
    outcome: "Learner can open and close a tiny interaction naturally.",
    replyPrompt: "Say good morning, hello, and thank you in one smooth sequence.",
    rewardBadge: "Greeting Guide",
    rewardXp: 15,
    acceptableResponses: ["ohayou gozaimasu", "konnichiwa", "arigatou gozaimasu", "おはようございます", "こんにちは"],
    modelPrompt: "Model a natural greeting flow that feels like entering a cafe or meeting someone for the first time.",
    guidedPrompt: "Roleplay a friendly encounter and ask the learner to greet, thank, and close politely.",
    checkpoint: "The learner completes a short greeting exchange with visible comfort.",
  }),
  createJapaneseSeed({
    id: "n5-survival-phrases",
    title: "Survival phrases",
    missionTitle: "Mission 14: Rescue yourself in live conversation",
    objective: "Give the learner rescue language they can use when real Japanese moves too fast.",
    storyHook: "You do not need perfect Japanese to survive. You need a few smart phrases that keep the conversation alive and kind.",
    checkpointLabel: "Survival phrase check",
    mode: "roleplay",
    demoPhrase: "wakarimasen, mou ichido onegaishimasu",
    pattern: "repair and help phrases",
    coverage: ["I don't understand", "One more time", "Slowly please", "Do you understand English?", "Please help me"],
    outcome: "Learner can slow down a conversation and ask for help instead of panicking.",
    replyPrompt: "Say I do not understand and one more time please.",
    rewardBadge: "Survival Speaker",
    rewardXp: 15,
    acceptableResponses: ["wakarimasen", "mou ichido onegaishimasu", "わかりません", "もういちど おねがいします"],
    modelPrompt: "Model calm rescue phrases with reassuring tone so the learner feels permission to use them.",
    guidedPrompt: "Pretend the tutor spoke too fast, then ask the learner to request repetition and slower speech.",
    checkpoint: "The learner can repair a confusing moment using two survival phrases.",
  }),
  createJapaneseSeed({
    id: "n5-first-sentence-pattern",
    title: "First sentence pattern",
    missionTitle: "Mission 15: Build your first full Japanese sentences",
    objective: "Introduce the classic A は B です pattern so the learner can finally say complete beginner sentences.",
    storyHook: "This is the moment Japanese stops being isolated words and starts becoming real sentences you can own.",
    checkpointLabel: "Sentence pattern check",
    mode: "speaking",
    demoPhrase: "watashi wa Rahul desu",
    pattern: "A wa B desu",
    coverage: ["A は B です", "Identity lines", "Object statements", "Place statements", "Polite sentence endings"],
    outcome: "Learner can form simple identity and object sentences without guessing English order.",
    replyPrompt: "Say I am Rahul and this is a book.",
    rewardBadge: "Sentence Starter",
    rewardXp: 20,
    acceptableResponses: ["watashi wa rahul desu", "kore wa hon desu", "わたしは ラフルです", "これは ほんです"],
    modelPrompt: "Model the beginner sentence pattern with a self-introduction and one object sentence.",
    guidedPrompt: "Ask the learner to use the pattern for self and object identification with one retry for rhythm.",
    checkpoint: "The learner produces two short desu-pattern sentences cleanly.",
  }),
  createJapaneseSeed({
    id: "n5-questions",
    title: "Questions and answers",
    missionTitle: "Mission 16: Ask and answer beginner questions",
    objective: "Move from statements into simple yes-no questions and calm beginner responses.",
    storyHook: "Now the conversation starts moving both ways. This mission teaches you how to ask and respond instead of only repeating.",
    checkpointLabel: "Question answer check",
    mode: "roleplay",
    demoPhrase: "kore wa hon desu ka. hai, sou desu",
    pattern: "desu ka questions",
    coverage: ["A は B ですか", "Yes answers", "No answers", "Basic response rhythm"],
    outcome: "Learner can ask and answer a tiny question without freezing.",
    replyPrompt: "Ask if it is a book, then answer yes politely.",
    rewardBadge: "Question Spark",
    rewardXp: 15,
    acceptableResponses: ["kore wa hon desu ka", "hai sou desu", "これは ほんですか", "はい そうです"],
    modelPrompt: "Model one question and two answer paths so the learner hears the rise, pause, and response flow.",
    guidedPrompt: "Run a yes-no question, then ask the learner to answer yes once and no once.",
    checkpoint: "The learner handles one full question-answer loop aloud.",
  }),
  createJapaneseSeed({
    id: "n5-particles",
    title: "Core particles",
    missionTitle: "Mission 17: Make sentences click with particles",
    objective: "Introduce the beginner particles that let Japanese sentences start making sense in real use.",
    storyHook: "Particles are tiny, but they control meaning. This mission helps you feel where water, school, topic, and place belong in a sentence.",
    checkpointLabel: "Particle mission check",
    mode: "speaking",
    demoPhrase: "mizu o nomimasu. gakkou ni ikimasu.",
    pattern: "wa, ga, o, ni, de, to, no",
    coverage: ["は", "が", "を", "に", "で", "と", "も", "の", "から/まで", "ね/よ"],
    outcome: "Learner can hear a few key particles inside natural beginner lines and use them with guidance.",
    replyPrompt: "Say I drink water and I go to school.",
    rewardBadge: "Particle Master",
    rewardXp: 20,
    acceptableResponses: ["mizu o nomimasu", "gakkou ni ikimasu", "みずをのみます", "がっこうにいきます"],
    modelPrompt: "Model useful particle sentences without turning the lesson into grammar overload.",
    guidedPrompt: "Ask the learner for one object sentence and one destination sentence, then polish the particle only if needed.",
    checkpoint: "The learner says two practical particle sentences with understandable structure.",
  }),
  createJapaneseSeed({
    id: "n5-verb-basics",
    title: "Verb basics",
    missionTitle: "Mission 18: Speak with action verbs",
    objective: "Teach the most useful N5 verbs so the learner can talk about eating, drinking, going, seeing, and studying.",
    storyHook: "You can now say what you do, where you go, what you drink, and what you study. This mission gives Japanese movement.",
    checkpointLabel: "Verb basics check",
    mode: "speaking",
    demoPhrase: "tabemasu, nomimasu, ikimasu, benkyou shimasu",
    pattern: "starter polite verbs",
    coverage: ["Eat, drink, go, come", "See and hear", "Read and write", "Buy and speak", "Study and work"],
    outcome: "Learner can say common actions in present polite form with more control.",
    replyPrompt: "Say eat, drink, go, and study in polite form.",
    rewardBadge: "Action Starter",
    rewardXp: 20,
    acceptableResponses: ["tabemasu", "nomimasu", "ikimasu", "benkyou shimasu", "たべます", "のみます"],
    modelPrompt: "Model common action verbs like a day-in-Japan soundtrack so the learner hears what people actually say.",
    guidedPrompt: "Ask what the learner does, drinks, or studies using one short verb answer at a time.",
    checkpoint: "The learner responds with at least three useful polite verbs.",
  }),
  createJapaneseSeed({
    id: "n5-verb-forms",
    title: "Verb forms",
    missionTitle: "Mission 19: Hear how verbs change shape",
    objective: "Introduce the forms beginners hear all the time so they can notice tense and request patterns earlier.",
    storyHook: "Japanese verbs bend to show requests, past actions, and negatives. This mission trains your ear before the forms overwhelm you.",
    checkpointLabel: "Verb form check",
    mode: "listening",
    demoPhrase: "tabemasu, tabenai, tabete, tabeta",
    pattern: "masu, nai, te, and ta contrasts",
    coverage: ["ます form", "Negative form", "Past form", "て form", "Dictionary-form awareness"],
    outcome: "Learner can hear that verbs change shape and can repeat the key beginner forms.",
    replyPrompt: "Repeat eat, do not eat, please eat, and ate.",
    rewardBadge: "Verb Shape Badge",
    rewardXp: 20,
    acceptableResponses: ["tabemasu", "tabenai", "tabete", "tabeta", "たべます", "たべない"],
    modelPrompt: "Model the same verb through four useful forms so the learner hears contrast before memorizing rules.",
    guidedPrompt: "Ask the learner to repeat the four forms, then identify which one sounds like the past.",
    checkpoint: "The learner can repeat and distinguish the core starter verb shapes.",
  }),
  createJapaneseSeed({
    id: "n5-adjectives",
    title: "Adjectives",
    missionTitle: "Mission 20: Describe the world in Japanese",
    objective: "Make Japanese description feel simple by introducing useful い-adjectives and な-adjectives in speech.",
    storyHook: "Food, weather, rooms, and people need description. This mission lets you say more than just nouns and verbs.",
    checkpointLabel: "Adjective check",
    mode: "speaking",
    demoPhrase: "oishii desu. shizuka desu.",
    pattern: "i-adjective and na-adjective basics",
    coverage: ["い-adjectives", "な-adjectives", "Positive forms", "Negative forms", "Past description"],
    outcome: "Learner can describe food, weather, and places in short natural lines.",
    replyPrompt: "Say it is delicious and it is quiet.",
    rewardBadge: "Description Starter",
    rewardXp: 20,
    acceptableResponses: ["oishii desu", "shizuka desu", "おいしいです", "しずかです"],
    modelPrompt: "Model one food reaction and one place description so adjectives land inside real use.",
    guidedPrompt: "Ask the learner how the food is and how the room is, then clean up one adjective ending.",
    checkpoint: "The learner gives two short adjective sentences with good clarity.",
  }),
  createJapaneseSeed({
    id: "n5-grammar-patterns",
    title: "Grammar sentence patterns",
    missionTitle: "Mission 21: Unlock the core N5 grammar patterns",
    objective: "Introduce the most useful N5 patterns through speaking tasks instead of textbook explanation blocks.",
    storyHook: "Now you start sounding like someone who can really manage a beginner conversation. This mission opens the grammar patterns people actually use.",
    checkpointLabel: "Grammar mission check",
    mode: "roleplay",
    demoPhrase: "mizu o nonde kudasai. suwari te mo ii desu.",
    pattern: "please, may, want, because, and other N5 patterns",
    coverage: ["〜てください", "〜てもいいです", "〜ています", "〜たいです", "〜がほしいです", "〜ながら", "〜つもりです", "〜とおもいます"],
    outcome: "Learner can hear and repeat key N5 patterns in usable lines.",
    replyPrompt: "Say please drink water and you may sit here.",
    rewardBadge: "Grammar Starter",
    rewardXp: 25,
    acceptableResponses: ["nonde kudasai", "suwatte mo ii desu", "のんでください", "すわってもいいです"],
    modelPrompt: "Model high-value N5 patterns as tiny live situations, not abstract grammar lectures.",
    guidedPrompt: "Run one polite request and one permission response, then retry the more difficult pattern.",
    checkpoint: "The learner uses two core grammar patterns in context.",
  }),
  createJapaneseSeed({
    id: "n5-counters",
    title: "Counters",
    missionTitle: "Mission 22: Count the Japanese way",
    objective: "Teach the counting suffixes beginners need for people, things, books, animals, and everyday objects.",
    storyHook: "In Japanese, numbers change depending on what you count. This mission helps you sound far more natural in shops and daily conversation.",
    checkpointLabel: "Counter check",
    mode: "speaking",
    demoPhrase: "hitotsu, futatsu, hitori, futari, issatsu",
    pattern: "general counters and classifier awareness",
    coverage: ["〜つ", "〜人", "〜本", "〜枚", "〜冊", "〜台", "〜回", "〜歳", "〜匹"],
    outcome: "Learner can answer simple counting questions more naturally than saying raw numbers only.",
    replyPrompt: "Say one thing, two things, one person, two people, and one book.",
    rewardBadge: "Counter Captain",
    rewardXp: 20,
    acceptableResponses: ["hitotsu", "futatsu", "hitori", "futari", "issatsu", "ひとつ", "ふたり"],
    modelPrompt: "Model counting through small travel and shopping examples so counters feel practical.",
    guidedPrompt: "Ask how many people, books, or items there are and have the learner answer aloud.",
    checkpoint: "The learner correctly says at least three beginner counters.",
  }),
];
