import { type SupplementalVocabularyBank } from "@/lib/japanese-vocab-supplement";

export const japaneseVocabularyExtraG: SupplementalVocabularyBank = {
  "travel-words": [
    ["りょこう", "ryokou", "travel"],
    ["りょこうしゃ", "ryokousha", "traveler"],
    ["よやく", "yoyaku", "reservation"],
    ["ホテルのへや", "hoteru no heya", "hotel room"],
    ["パスポート", "pasupooto", "passport"],
    ["にもつ", "nimotsu", "luggage"],
    ["ちず", "chizu", "map"],
    ["かんこう", "kankou", "sightseeing"],
    ["しゃしんをとります", "shashin o torimasu", "to take a photo"],
    ["のりかえ", "norikae", "transfer"],
    ["とうじょうけん", "toujouken", "boarding pass"],
    ["しゅっぱつじかん", "shuppatsu jikan", "departure time"],
    ["とうちゃくじかん", "touchaku jikan", "arrival time"],
    ["あんない", "annai", "guidance"],
    ["りょかん", "ryokan", "Japanese inn"],
    ["おみやげ", "omiyage", "souvenir"],
    ["きっさてん", "kissaten", "coffee shop"],
    ["こくない", "kokunai", "domestic"],
  ],
  "question-words": [
    ["なに", "nani", "what"],
    ["だれ", "dare", "who"],
    ["どこ", "doko", "where"],
    ["いつ", "itsu", "when"],
    ["どう", "dou", "how"],
    ["どうして", "doushite", "why"],
    ["なぜ", "naze", "why"],
    ["どちら", "dochira", "which way"],
    ["どの", "dono", "which"],
    ["どんな", "donna", "what kind of"],
    ["どれくらい", "dore kurai", "how much or how long"],
    ["いくつ", "ikutsu", "how many or how old"],
    ["なんにん", "nan nin", "how many people"],
    ["なんじ", "nanji", "what time"],
    ["なんようび", "nan youbi", "what day of the week"],
    ["なんがつ", "nan gatsu", "what month"],
    ["なんにち", "nan nichi", "what date"],
    ["どこから", "doko kara", "from where"],
  ],
  "common-adverbs": [
    ["よく", "yoku", "often or well"],
    ["あまり", "amari", "not very"],
    ["ぜんぜん", "zenzen", "not at all"],
    ["いつも", "itsumo", "always"],
    ["ときどき", "tokidoki", "sometimes"],
    ["たいてい", "taitei", "usually"],
    ["たぶん", "tabun", "probably"],
    ["ほんとうに", "hontou ni", "really"],
    ["もちろん", "mochiron", "of course"],
    ["いっしょに", "issho ni", "together"],
    ["ひとりで", "hitori de", "alone"],
    ["たくさん", "takusan", "a lot"],
    ["すこし", "sukoshi", "a little"],
    ["もう", "mou", "already or more"],
    ["まだ", "mada", "still or not yet"],
    ["すぐに", "sugu ni", "immediately"],
    ["とても", "totemo", "very"],
    ["ゆっくり", "yukkuri", "slowly"],
  ],
  "basic-expressions": [
    ["はい", "hai", "yes"],
    ["いいえ", "iie", "no"],
    ["そうです", "sou desu", "that is right"],
    ["ちがいます", "chigaimasu", "that is not correct"],
    ["そうですね", "sou desu ne", "let me see or that's right"],
    ["どうも", "doumo", "thanks or hello"],
    ["なるほど", "naruhodo", "I see"],
    ["もちろんです", "mochiron desu", "of course"],
    ["たぶんそうです", "tabun sou desu", "probably so"],
    ["だめです", "dame desu", "it is no good"],
    ["いいですよ", "ii desu yo", "it is fine"],
    ["しりません", "shirimasen", "I do not know"],
    ["わたしも", "watashi mo", "me too"],
    ["そうしましょう", "sou shimashou", "let's do that"],
    ["きをつけます", "ki o tsukemasu", "I will be careful"],
    ["すごい", "sugoi", "amazing"],
    ["ほんとうですか", "hontou desu ka", "really"],
    ["だいすきです", "daisuki desu", "I love it"],
  ],
};
