import { createJapaneseSeed } from "@/lib/japanese-seed";

export const japaneseN5PhaseHiragana = [
  createJapaneseSeed({
    id: "n5-hiragana-a-row",
    title: "Hiragana a-row",
    missionTitle: "Mission 13: Read your first Japanese letters",
    objective: "Teach あいうえお in English with voice-first guidance so the learner reads the first real hiragana row.",
    storyHook: "You see あいうえお for the first time and realize Japanese script is finally becoming readable.",
    checkpointLabel: "A-row reading check",
    mode: "listening",
    demoPhrase: "あ い う え お",
    pattern: "hiragana a-row",
    coverage: ["あいうえお", "Sound-to-symbol link", "First script confidence"],
    outcome: "Learner can read and say the hiragana a-row aloud.",
    replyPrompt: "Read あ い う え お in order.",
    acceptableResponses: ["あいうえお", "a i u e o"],
    modelPrompt: "Model the a-row as symbols the learner can already hear from aiueo.",
    guidedPrompt: "Ask the learner to read the five characters and repeat the hardest one once more.",
    checkpoint: "Learner clears the first hiragana row.",
    rewardBadge: "Hiragana Hero",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-hiragana-k-row",
    title: "Hiragana k-row",
    missionTitle: "Mission 14: Read かきくけこ",
    objective: "Connect the ka-row sounds to their hiragana symbols in a clean beginner voice lesson.",
    storyHook: "The sound map now becomes script. You can finally see and say かきくけこ as one system.",
    checkpointLabel: "K-row reading check",
    mode: "listening",
    demoPhrase: "か き く け こ",
    pattern: "hiragana k-row",
    coverage: ["かきくけこ", "Sound row to symbol row", "Reading confidence"],
    outcome: "Learner reads and says the hiragana k-row accurately.",
    replyPrompt: "Read か き く け こ in order.",
    acceptableResponses: ["かきくけこ", "ka ki ku ke ko"],
    modelPrompt: "Model the k-row visually and vocally so the learner sees the row they already know by sound.",
    guidedPrompt: "Ask the learner to read each character, then read the whole row once smoothly.",
    checkpoint: "Learner completes the hiragana k-row.",
    rewardBadge: "Kana Row Starter",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-hiragana-s-t-rows",
    title: "Hiragana s and t rows",
    missionTitle: "Mission 15: Read the rows with special sounds",
    objective: "Teach さしすせそ and たちつてと with voice emphasis on し, ち, and つ.",
    storyHook: "These rows teach you that Japanese letters sometimes hide special sounds, but they are still learnable.",
    checkpointLabel: "S and T row reading",
    mode: "listening",
    demoPhrase: "さ し す せ そ, た ち つ て と",
    pattern: "hiragana s and t rows",
    coverage: ["さしすせそ", "たちつてと", "し ち つ contrast"],
    outcome: "Learner reads two key hiragana rows with better precision.",
    replyPrompt: "Read the s-row and t-row once in order.",
    acceptableResponses: ["さしすせそ", "たちつてと", "sa shi su se so", "ta chi tsu te to"],
    modelPrompt: "Model the rows with extra clarity on し, ち, and つ so reading and sound stay connected.",
    guidedPrompt: "Ask the learner to read both rows and retry つ once more if needed.",
    checkpoint: "Learner reads the s-row and t-row with a usable special-sound contrast.",
    rewardBadge: "Row Reader",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-hiragana-n-h-rows",
    title: "Hiragana n and h rows",
    missionTitle: "Mission 16: Expand hiragana reading power",
    objective: "Teach the n-row and h-row with clear English support for ふ.",
    storyHook: "The more rows you read, the more Japanese words stop looking impossible and start looking familiar.",
    checkpointLabel: "N and H row reading",
    mode: "listening",
    demoPhrase: "な に ぬ ね の, は ひ ふ へ ほ",
    pattern: "hiragana n and h rows",
    coverage: ["な-row", "は-row", "ふ as a special beginner sound"],
    outcome: "Learner reads and says two more hiragana rows confidently.",
    replyPrompt: "Read the n-row and h-row aloud.",
    acceptableResponses: ["なにぬねの", "はひふへほ", "na ni nu ne no", "ha hi fu he ho"],
    modelPrompt: "Model the rows clearly and explain ふ in one short English line before continuing.",
    guidedPrompt: "Ask the learner to read both rows and pause briefly on ふ for one cleaner pass.",
    checkpoint: "Learner handles both rows and notices ふ correctly.",
    rewardBadge: "Reading Builder",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-hiragana-m-y-r-w",
    title: "Remaining hiragana rows",
    missionTitle: "Mission 17: Finish the basic hiragana chart",
    objective: "Complete the remaining hiragana rows and symbols so the learner owns the full 46-character chart.",
    storyHook: "This mission completes the core hiragana map and turns the script from mystery into something familiar.",
    checkpointLabel: "Full hiragana chart ready",
    mode: "speaking",
    demoPhrase: "ま み む め も, や ゆ よ, ら り る れ ろ, わ を ん",
    pattern: "remaining hiragana rows",
    coverage: ["ま-row", "やゆよ", "ら-row", "わをん", "46-character completion"],
    outcome: "Learner can move across the remaining basic hiragana chart with confidence.",
    replyPrompt: "Read the remaining rows and the final symbols in order.",
    acceptableResponses: ["まみむめも", "やゆよ", "らりるれろ", "わをん"],
    modelPrompt: "Model the remaining rows as the final pieces of the hiragana map.",
    guidedPrompt: "Ask the learner to read each group and then say ん once clearly at the end.",
    checkpoint: "Learner completes the full basic hiragana set.",
    rewardBadge: "Hiragana Chart Complete",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-hiragana-words",
    title: "Hiragana words",
    missionTitle: "Mission 18: Read your first real Japanese words",
    objective: "Use easy hiragana words so script practice turns into meaning and fun.",
    storyHook: "Reading すし, ねこ, and にほん is the first moment many beginners feel real joy in Japanese.",
    checkpointLabel: "Hiragana word mission",
    mode: "speaking",
    demoPhrase: "すし, ねこ, いぬ, にほん",
    pattern: "hiragana word reading",
    coverage: ["Food words", "Animal words", "Place words", "Meaning plus reading"],
    outcome: "Learner reads familiar hiragana words instead of isolated symbols only.",
    replyPrompt: "Read sushi, cat, dog, and Japan aloud.",
    acceptableResponses: ["すし", "ねこ", "いぬ", "にほん", "sushi", "neko"],
    modelPrompt: "Model beginner hiragana words with natural meaning and rhythm so script feels alive.",
    guidedPrompt: "Ask the learner to read each word and then say which one means Japan.",
    checkpoint: "Learner reads four common hiragana words successfully.",
    rewardBadge: "Word Reader",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-hiragana-dakuon",
    title: "Hiragana dakuon",
    missionTitle: "Mission 19: Add voiced hiragana sounds",
    objective: "Teach voiced hiragana like が and ざ so the learner can handle a wider range of N5 words.",
    storyHook: "Two small marks change the sound and unlock many real words. This mission trains that jump.",
    checkpointLabel: "Dakuon check",
    mode: "repeat",
    demoPhrase: "が ぎ ぐ げ ご, ざ じ ず ぜ ぞ",
    pattern: "dakuon practice",
    coverage: ["が-row", "ざ-row", "だ-row", "ば-row", "Voiced-word practice"],
    outcome: "Learner can hear and repeat core dakuon sounds with less confusion.",
    replyPrompt: "Repeat the が-row and ざ-row once clearly.",
    acceptableResponses: ["がぎぐげご", "ざじずぜぞ", "ga gi gu ge go"],
    modelPrompt: "Model the voiced rows and connect them to words like がくせい and でんわ.",
    guidedPrompt: "Ask the learner to repeat the rows and one dakuon word.",
    checkpoint: "Learner completes voiced row practice successfully.",
    rewardBadge: "Voiced Sound Badge",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-hiragana-handakuon-yoon",
    title: "Handakuon and yoon",
    missionTitle: "Mission 20: Handle circles and glide sounds",
    objective: "Teach ぱ-row sounds and small や ゆ よ combinations in a friendly speaking loop.",
    storyHook: "A small circle and a small ya-yu-yo can completely change a word. This mission makes those changes feel manageable.",
    checkpointLabel: "Handakuon and yoon",
    mode: "repeat",
    demoPhrase: "ぱ ぴ ぷ ぺ ぽ, きゃ きゅ きょ",
    pattern: "handakuon and yoon",
    coverage: ["ぱ-row", "きゃ/きゅ/きょ", "しゃ/しゅ/しょ", "ちゃ/ちゅ/ちょ"],
    outcome: "Learner can repeat beginner handakuon and yoon sounds with more control.",
    replyPrompt: "Repeat the ぱ-row and one yoon set clearly.",
    acceptableResponses: ["ぱぴぷぺぽ", "きゃきゅきょ", "pa pi pu pe po"],
    modelPrompt: "Model the ぱ-row and a few yoon combinations through fun beginner words.",
    guidedPrompt: "Ask the learner to repeat one row and one glide set, then retry the harder one.",
    checkpoint: "Learner handles both handakuon and yoon practice.",
    rewardBadge: "Glide Sound Badge",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-hiragana-sokuon-choun",
    title: "Sokuon and long vowels",
    missionTitle: "Mission 21: Hear pauses and long sound changes",
    objective: "Teach small っ and long vowels so the learner hears timing differences that change meaning.",
    storyHook: "A tiny pause can change a word completely. This mission teaches the timing details that make Japanese sound real.",
    checkpointLabel: "Timing contrast check",
    mode: "repeat",
    demoPhrase: "がっこう, きっぷ, おばさん, おばあさん",
    pattern: "sokuon and long vowels",
    coverage: ["Small っ pause", "Double consonants", "Long vowels", "Meaning contrast"],
    outcome: "Learner can repeat and notice timing-based differences more clearly.",
    replyPrompt: "Repeat gakkou, kippu, obasan, and obaasan with clear timing.",
    acceptableResponses: ["gakkou", "kippu", "obasan", "obaasan", "がっこう", "きっぷ"],
    modelPrompt: "Model pause words and long-vowel pairs so the learner hears how meaning can shift with timing.",
    guidedPrompt: "Ask the learner to repeat the pause word and the long-vowel contrast pair.",
    checkpoint: "Learner finishes the hiragana timing mission.",
    rewardBadge: "Timing Master",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-hiragana-reading-writing",
    title: "Full hiragana practice",
    missionTitle: "Mission 22: Lock in the full hiragana system",
    objective: "Review the full hiragana chart through reading, writing awareness, and confident voice practice in English.",
    storyHook: "This is the consolidation mission where the hiragana chart stops feeling fragile and starts feeling like yours.",
    checkpointLabel: "Hiragana mastery check",
    mode: "checkpoint",
    demoPhrase: "あいうえお, かきくけこ, すし, にほん",
    pattern: "full hiragana review",
    coverage: ["Full chart review", "Word reading", "Writing awareness", "Special sounds recap"],
    outcome: "Learner can move through hiragana with stronger confidence before katakana begins.",
    replyPrompt: "Read one row, one word, and one special-sound word clearly.",
    acceptableResponses: ["あいうえお", "かきくけこ", "すし", "にほん"],
    modelPrompt: "Model a compact hiragana review that feels like a success lap rather than a heavy exam.",
    guidedPrompt: "Ask the learner for one row, one word, and one special sound example to complete the review.",
    checkpoint: "Learner is ready to move into katakana.",
    rewardBadge: "Hiragana Hero",
    rewardXp: 20,
  }),
];
