import { createJapaneseSeed } from "@/lib/japanese-seed";

export const japaneseN5PhaseLanguage = [
  createJapaneseSeed({
    id: "n5-numbers-basics",
    title: "Numbers 0 to 10",
    missionTitle: "Mission 32: Count from zero",
    objective: "Teach the first Japanese numbers in English through voice practice and quick real-life prompts.",
    storyHook: "Prices, time, and age all begin here. This mission makes Japanese numbers feel approachable from the first ten.",
    checkpointLabel: "0 to 10 count check",
    mode: "speaking",
    demoPhrase: "rei, ichi, ni, san, yon, go, roku, nana, hachi, kyuu, juu",
    pattern: "numbers 0 to 10",
    coverage: ["0 to 10", "Alternative forms", "Basic counting confidence"],
    outcome: "Learner can say the core beginner numbers aloud.",
    replyPrompt: "Count from zero to ten clearly.",
    acceptableResponses: ["rei ichi ni san yon go roku nana hachi kyuu juu", "いち に さん よん ご"],
    modelPrompt: "Model zero to ten in a calm practical rhythm rather than a rushed chant.",
    guidedPrompt: "Ask the learner to count to ten and retry four and seven once for confidence.",
    checkpoint: "Learner completes the first number ladder.",
    rewardBadge: "Number Ninja",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-numbers-teens-tens",
    title: "Teens and tens",
    missionTitle: "Mission 33: Build bigger numbers",
    objective: "Teach 11 to 100 by showing the stacking pattern in clear English support.",
    storyHook: "Once you understand the pattern, bigger Japanese numbers suddenly stop looking scary.",
    checkpointLabel: "Bigger number check",
    mode: "speaking",
    demoPhrase: "juuichi, juuni, nijuu, sanjuu, kyuujuukyuu",
    pattern: "teens and tens",
    coverage: ["11 to 20", "30 to 90", "Pattern stacking", "21 and 99 examples"],
    outcome: "Learner can form and speak larger beginner numbers.",
    replyPrompt: "Say eleven, twenty, thirty-five, and ninety-nine.",
    acceptableResponses: ["juuichi", "nijuu", "sanjuugo", "kyuujuukyuu", "じゅういち", "きゅうじゅうきゅう"],
    modelPrompt: "Model the Japanese stacking pattern so the learner hears the logic, not random memorization.",
    guidedPrompt: "Ask for one teen number and two combined numbers, then repeat the hardest once.",
    checkpoint: "Learner successfully forms bigger beginner numbers.",
    rewardBadge: "Count Builder",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-money-age",
    title: "Money and age",
    missionTitle: "Mission 34: Talk about prices and age",
    objective: "Teach yen amounts and age questions through practical English explanations and spoken drills.",
    storyHook: "You buy something and someone asks how old you are. This mission prepares both moments.",
    checkpointLabel: "Money and age check",
    mode: "roleplay",
    demoPhrase: "hyaku en, sen en, nansai desu ka",
    pattern: "money and age",
    coverage: ["Yen amounts", "How much is it?", "How old are you?", "Age counters"],
    outcome: "Learner can ask a price and answer or understand a simple age question.",
    replyPrompt: "Ask how much it is and then say twenty years old.",
    acceptableResponses: ["ikura desu ka", "hatachi", "これは いくらですか", "はたち"],
    modelPrompt: "Model a tiny shop exchange and a simple age answer with friendly pacing.",
    guidedPrompt: "Ask the learner one money line and one age line, then retry the harder one.",
    checkpoint: "Learner clears the money and age mission.",
    rewardBadge: "Yen Counter",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-time-weekdays",
    title: "Time and weekdays",
    missionTitle: "Mission 35: Tell time in Japan",
    objective: "Teach clock time and weekdays so the learner can answer basic schedule questions in Japanese.",
    storyHook: "Waking up at six and meeting on Monday are simple ideas, but saying them in Japanese feels like progress.",
    checkpointLabel: "Time mission check",
    mode: "speaking",
    demoPhrase: "rokuji, getsuyoubi, nichiyoubi",
    pattern: "time and weekdays",
    coverage: ["What time is it?", "1 to 10 o'clock", "Weekdays", "Schedule language"],
    outcome: "Learner can say a time and recognize or produce a weekday.",
    replyPrompt: "Say six o'clock and Monday in Japanese.",
    acceptableResponses: ["rokuji", "getsuyoubi", "ろくじ", "げつようび"],
    modelPrompt: "Model common time and weekday expressions in one small daily routine scene.",
    guidedPrompt: "Ask the learner what time it is and what day it is, then repeat the answer smoothly.",
    checkpoint: "Learner can answer a small schedule prompt.",
    rewardBadge: "Schedule Starter",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-people-family",
    title: "People and family words",
    missionTitle: "Mission 36: Talk about people around you",
    objective: "Teach the first family and people words in English so the learner can describe close relationships.",
    storyHook: "The first meaningful vocabulary usually comes from the people you know. This mission turns that into Japanese.",
    checkpointLabel: "People and family check",
    mode: "speaking",
    demoPhrase: "watashi, tomodachi, kazoku, haha, chichi",
    pattern: "people and family vocabulary",
    coverage: ["I and you", "Friend", "Family", "Mother and father", "Brother and sister"],
    outcome: "Learner can say a few basic people and family words clearly.",
    replyPrompt: "Say I, friend, family, mother, and father in Japanese.",
    acceptableResponses: ["watashi", "tomodachi", "kazoku", "haha", "chichi", "わたし", "ともだち"],
    modelPrompt: "Model family and people words with gentle real-life context instead of a flat list.",
    guidedPrompt: "Ask the learner who is in their family and have them answer with short word responses.",
    checkpoint: "Learner clears the first people vocabulary set.",
    rewardBadge: "People Builder",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-food-drink",
    title: "Food and drink words",
    missionTitle: "Mission 37: Build your first menu vocabulary",
    objective: "Teach food and drink words the learner will use in cafes, restaurants, and daily life.",
    storyHook: "Water, tea, sushi, ramen, and bread are among the first Japanese words many learners truly use.",
    checkpointLabel: "Food vocabulary check",
    mode: "speaking",
    demoPhrase: "mizu, ocha, sushi, raamen, pan",
    pattern: "food and drink vocabulary",
    coverage: ["Water", "Tea", "Coffee", "Rice", "Bread", "Sushi", "Ramen", "Fish", "Meat", "Vegetables"],
    outcome: "Learner can say several core food and drink words with confidence.",
    replyPrompt: "Say water, tea, sushi, ramen, and bread in Japanese.",
    acceptableResponses: ["mizu", "ocha", "sushi", "raamen", "pan", "みず", "おちゃ"],
    modelPrompt: "Model menu vocabulary through a small cafe scene instead of a memorization list.",
    guidedPrompt: "Ask the learner what they want to eat or drink and let them answer in short words first.",
    checkpoint: "Learner can use a useful beginner menu word bank.",
    rewardBadge: "Menu Starter",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-places-objects",
    title: "Places and objects",
    missionTitle: "Mission 38: Name the places and things around you",
    objective: "Teach house, school, station, shop, book, bag, phone, and similar daily words in spoken English-guided practice.",
    storyHook: "You start seeing words for places and objects everywhere. This mission gives you the nouns that unlock daily scenes.",
    checkpointLabel: "Places and objects check",
    mode: "speaking",
    demoPhrase: "ie, gakkou, eki, hon, kaban, denwa",
    pattern: "daily nouns",
    coverage: ["House", "School", "Station", "Shop", "Restaurant", "Hotel", "Book", "Bag", "Phone", "Car"],
    outcome: "Learner can say and recognize common places and objects.",
    replyPrompt: "Say house, school, station, book, bag, and phone in Japanese.",
    acceptableResponses: ["ie", "gakkou", "eki", "hon", "kaban", "denwa", "いえ", "えき"],
    modelPrompt: "Model daily nouns as things you carry and places you visit in a single day.",
    guidedPrompt: "Ask the learner what they have and where they are going using short noun answers.",
    checkpoint: "Learner clears the places and objects mission.",
    rewardBadge: "Daily World Badge",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-weather-colors",
    title: "Weather and colors",
    missionTitle: "Mission 39: Describe simple everyday things",
    objective: "Teach weather and color basics so the learner can start describing what the day feels like.",
    storyHook: "Sunny, rainy, hot, cold, white, and new are small words, but they make Japanese feel much more alive.",
    checkpointLabel: "Description starter",
    mode: "speaking",
    demoPhrase: "hare, ame, atsui, samui, shiroi",
    pattern: "simple description vocabulary",
    coverage: ["Sunny", "Rain", "Snow", "Hot", "Cold", "White", "New", "Old"],
    outcome: "Learner can describe simple weather or item qualities in basic Japanese.",
    replyPrompt: "Say sunny, rain, hot, cold, and white in Japanese.",
    acceptableResponses: ["hare", "ame", "atsui", "samui", "shiroi", "はれ", "あめ"],
    modelPrompt: "Model weather and color words like small observations a traveler would naturally say.",
    guidedPrompt: "Ask the learner how the weather is and what color something is, then repeat key words.",
    checkpoint: "Learner begins describing the world in Japanese.",
    rewardBadge: "Description Spark",
    rewardXp: 10,
  }),
  createJapaneseSeed({
    id: "n5-greetings-polite",
    title: "Greetings and polite words",
    missionTitle: "Mission 40: Sound respectful from the start",
    objective: "Teach the most important greetings and polite words in English-led practice so the learner sounds warm and safe.",
    storyHook: "A good greeting changes the whole interaction. This mission helps you sound human and respectful immediately.",
    checkpointLabel: "Greeting confidence check",
    mode: "roleplay",
    demoPhrase: "ohayou gozaimasu, konnichiwa, arigatou gozaimasu, sumimasen",
    pattern: "greetings and politeness",
    coverage: ["Good morning", "Hello", "Good evening", "Thank you", "Excuse me", "Please", "You're welcome"],
    outcome: "Learner can greet, thank, and sound polite in a short exchange.",
    replyPrompt: "Say good morning, thank you, and excuse me in Japanese.",
    acceptableResponses: ["ohayou gozaimasu", "arigatou gozaimasu", "sumimasen", "おはようございます", "ありがとうございます"],
    modelPrompt: "Model a friendly greeting exchange that a learner could actually use on day one in Japan.",
    guidedPrompt: "Roleplay a tiny greeting moment and have the learner respond politely.",
    checkpoint: "Learner can open and soften a conversation with polite Japanese.",
    rewardBadge: "Politeness Badge",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-survival-phrases",
    title: "Survival phrases",
    missionTitle: "Mission 41: Rescue the conversation",
    objective: "Teach the beginner repair phrases that help the learner slow things down or ask for help.",
    storyHook: "You do not need perfect Japanese to survive. You need a few rescue phrases that keep you calm and understood.",
    checkpointLabel: "Survival phrase check",
    mode: "roleplay",
    demoPhrase: "wakarimasen, mou ichido onegaishimasu, yukkuri onegaishimasu",
    pattern: "repair phrases",
    coverage: ["I don't understand", "One more time please", "Slowly please", "Do you understand English?", "Please help me"],
    outcome: "Learner can recover from confusion without giving up.",
    replyPrompt: "Say I do not understand and one more time please.",
    acceptableResponses: ["wakarimasen", "mou ichido onegaishimasu", "わかりません", "もういちど おねがいします"],
    modelPrompt: "Model rescue phrases with reassuring tone so the learner feels empowered, not embarrassed.",
    guidedPrompt: "Pretend the tutor spoke too fast and ask the learner to request help using the target phrases.",
    checkpoint: "Learner completes the survival-language mission.",
    rewardBadge: "Survival Speaker",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-first-sentences",
    title: "First sentence pattern",
    missionTitle: "Mission 42: Build complete beginner sentences",
    objective: "Teach A は B です through English explanation and voice-first practice so the learner forms real sentences.",
    storyHook: "This is the moment Japanese becomes a sentence language instead of a pile of words.",
    checkpointLabel: "Sentence pattern check",
    mode: "speaking",
    demoPhrase: "watashi wa Rahul desu. kore wa hon desu.",
    pattern: "A wa B desu",
    coverage: ["I am ...", "This is ...", "That place is ...", "Polite sentence ending"],
    outcome: "Learner can produce short complete beginner sentences.",
    replyPrompt: "Say I am Rahul and this is a book.",
    acceptableResponses: ["watashi wa rahul desu", "kore wa hon desu", "わたしは ラフルです", "これは ほんです"],
    modelPrompt: "Model one self-introduction sentence and one object sentence as the learner's first real grammar win.",
    guidedPrompt: "Ask the learner to use the pattern for self and for one object, then repeat it more naturally.",
    checkpoint: "Learner produces two full beginner sentences.",
    rewardBadge: "Sentence Starter",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-questions-answers",
    title: "Questions and answers",
    missionTitle: "Mission 43: Make conversation move both ways",
    objective: "Teach A は B ですか and the core yes-no answers so the learner can ask and respond simply.",
    storyHook: "Now conversation becomes two-way. This mission adds the first real question and answer loop.",
    checkpointLabel: "Question loop check",
    mode: "roleplay",
    demoPhrase: "kore wa hon desu ka. hai, sou desu. iie, chigaimasu.",
    pattern: "basic question and answer",
    coverage: ["Is this...?", "Yes that is right", "No that is different", "Question rhythm"],
    outcome: "Learner can ask and answer a simple beginner question.",
    replyPrompt: "Ask if this is a book, answer yes once, then answer no once.",
    acceptableResponses: ["kore wa hon desu ka", "hai sou desu", "iie chigaimasu", "これは ほんですか"],
    modelPrompt: "Model the question loop with a small pause so the learner hears the shape of beginner conversation.",
    guidedPrompt: "Ask one yes-no question and have the learner respond both positively and negatively.",
    checkpoint: "Learner clears the first question-answer loop.",
    rewardBadge: "Question Spark",
    rewardXp: 15,
  }),
];
