import { createJapaneseSeed } from "@/lib/japanese-seed";

export const japaneseN5PhaseApplication = [
  createJapaneseSeed({
    id: "n5-particles-basic",
    title: "Core particles 1",
    missionTitle: "Mission 44: Make sentences click",
    objective: "Teach は, が, を, and に in clear English so the learner starts hearing what holds Japanese sentences together.",
    storyHook: "Particles are tiny, but once you feel them, Japanese begins to make much more sense.",
    checkpointLabel: "Particle basics check",
    mode: "speaking",
    demoPhrase: "watashi wa Rahul desu. mizu o nomimasu. gakkou ni ikimasu.",
    pattern: "basic particles",
    coverage: ["は topic", "が subject", "を object", "に destination and time"],
    outcome: "Learner can use the most basic particles in practical lines.",
    replyPrompt: "Say I am Rahul, I drink water, and I go to school.",
    acceptableResponses: ["watashi wa rahul desu", "mizu o nomimasu", "gakkou ni ikimasu", "みずをのみます"],
    modelPrompt: "Model practical particle sentences and explain only the minimal English needed to keep speaking moving.",
    guidedPrompt: "Ask for one self sentence, one object sentence, and one destination sentence.",
    checkpoint: "Learner clears the core particle mission.",
    rewardBadge: "Particle Master",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-particles-extended",
    title: "Core particles 2",
    missionTitle: "Mission 45: Add relationship and nuance particles",
    objective: "Teach で, と, も, の, から, まで, か, ね, and よ through simple spoken examples in English.",
    storyHook: "Now you begin linking places, people, possession, and soft conversation tone together like a real beginner speaker.",
    checkpointLabel: "Extended particle check",
    mode: "speaking",
    demoPhrase: "resutoran de tabemasu. watashi no hon. tomodachi to ikimasu.",
    pattern: "extended particle use",
    coverage: ["で", "と", "も", "の", "から", "まで", "か", "ね", "よ"],
    outcome: "Learner can notice and use more relationship particles inside practical Japanese.",
    replyPrompt: "Say I eat at a restaurant, my book, and I go with a friend.",
    acceptableResponses: ["resutoran de tabemasu", "watashi no hon", "tomodachi to ikimasu", "レストランでたべます"],
    modelPrompt: "Model relationship particles inside useful travel and daily-life lines rather than abstract grammar talk.",
    guidedPrompt: "Ask for one place sentence, one possession sentence, and one with-a-friend sentence.",
    checkpoint: "Learner completes the extended particle mission.",
    rewardBadge: "Particle Builder",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-verbs-basic",
    title: "Verb basics",
    missionTitle: "Mission 46: Speak with action words",
    objective: "Teach the core N5 polite verbs so the learner can talk about eating, drinking, going, seeing, and studying.",
    storyHook: "Once verbs arrive, Japanese suddenly feels much more alive and personal.",
    checkpointLabel: "Verb basics check",
    mode: "speaking",
    demoPhrase: "tabemasu, nomimasu, ikimasu, mimasu, benkyou shimasu",
    pattern: "polite verb basics",
    coverage: ["Eat", "Drink", "Go", "Come", "See", "Read", "Write", "Study", "Work"],
    outcome: "Learner can say the most useful beginner actions in polite form.",
    replyPrompt: "Say eat, drink, go, see, and study in Japanese.",
    acceptableResponses: ["tabemasu", "nomimasu", "ikimasu", "mimasu", "benkyou shimasu", "たべます"],
    modelPrompt: "Model daily-life verbs as actions a real learner might do throughout the day.",
    guidedPrompt: "Ask the learner what they eat, drink, or study using single-verb replies first.",
    checkpoint: "Learner completes the core verb mission.",
    rewardBadge: "Action Starter",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-verb-forms",
    title: "Verb forms",
    missionTitle: "Mission 47: Hear verbs change shape",
    objective: "Teach the basic polite, negative, past, dictionary, nai, ta, and te forms through English support and repeated speech.",
    storyHook: "Japanese verbs bend in ways that look strange at first, but this mission helps your ear settle into the pattern.",
    checkpointLabel: "Verb form mission",
    mode: "listening",
    demoPhrase: "tabemasu, tabemasen, tabemashita, tabenai, tabete, tabeta",
    pattern: "verb form awareness",
    coverage: ["Polite present", "Polite negative", "Polite past", "Dictionary form", "Nai", "Ta", "Te"],
    outcome: "Learner recognizes how a verb changes shape across useful beginner forms.",
    replyPrompt: "Repeat the forms for eat from polite present through ta-form.",
    acceptableResponses: ["tabemasu", "tabemasen", "tabemashita", "tabenai", "tabete", "tabeta", "たべます"],
    modelPrompt: "Model one core verb through several shapes so the learner hears the form family, not random fragments.",
    guidedPrompt: "Ask the learner to repeat the forms and identify which one sounds like the past.",
    checkpoint: "Learner completes the basic verb-form mission.",
    rewardBadge: "Verb Shape Badge",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-adjectives",
    title: "Adjectives",
    missionTitle: "Mission 48: Describe food, weather, and places",
    objective: "Teach common い-adjectives and な-adjectives in English through practical spoken Japanese.",
    storyHook: "Now you can say what is delicious, quiet, beautiful, cheap, cold, or convenient.",
    checkpointLabel: "Adjective mission",
    mode: "speaking",
    demoPhrase: "oishii desu. samui desu. shizuka desu. kirei desu.",
    pattern: "i and na adjectives",
    coverage: ["い-adjectives", "な-adjectives", "Positive", "Negative", "Past forms"],
    outcome: "Learner can describe simple things with more personality.",
    replyPrompt: "Say it is delicious, cold, quiet, and beautiful.",
    acceptableResponses: ["oishii desu", "samui desu", "shizuka desu", "kirei desu", "おいしいです"],
    modelPrompt: "Model simple descriptive lines tied to food, weather, and rooms rather than abstract explanation.",
    guidedPrompt: "Ask the learner how the food is and how the room is, then retry one adjective naturally.",
    checkpoint: "Learner completes the adjective mission.",
    rewardBadge: "Description Starter",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-grammar-patterns-1",
    title: "Grammar patterns 1",
    missionTitle: "Mission 49: Make requests and permissions",
    objective: "Teach early N5 patterns like てください, てもいいです, and てはいけません in English-led spoken practice.",
    storyHook: "Requests and permissions are everywhere in real life. This mission makes those sentence patterns usable.",
    checkpointLabel: "Pattern set one",
    mode: "roleplay",
    demoPhrase: "mizu o nonde kudasai. koko de suwatte mo ii desu. koko de tabete wa ikemasen.",
    pattern: "request and permission patterns",
    coverage: ["〜てください", "〜てもいいです", "〜てはいけません", "〜ています"],
    outcome: "Learner can repeat and use a few important request and permission patterns.",
    replyPrompt: "Say please drink water and you may sit here.",
    acceptableResponses: ["nonde kudasai", "suwatte mo ii desu", "のんでください", "すわってもいいです"],
    modelPrompt: "Model the patterns as short real-life lines that a traveler could actually hear and use.",
    guidedPrompt: "Ask the learner to request one action and give one permission response.",
    checkpoint: "Learner clears the first grammar-pattern set.",
    rewardBadge: "Grammar Starter",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-grammar-patterns-2",
    title: "Grammar patterns 2",
    missionTitle: "Mission 50: Talk about wants, plans, and reasons",
    objective: "Teach more N5 patterns like たいです, がほしいです, から, つもりです, and とおもいます through spoken examples.",
    storyHook: "Now your Japanese can express want, intention, and opinion instead of only facts.",
    checkpointLabel: "Pattern set two",
    mode: "roleplay",
    demoPhrase: "nihon e ikitai desu. mizu ga hoshii desu. atsui desu kara mizu o nomimasu.",
    pattern: "wants and reasons",
    coverage: ["〜たいです", "〜がほしいです", "〜から", "〜つもりです", "〜とおもいます"],
    outcome: "Learner can express desire, reason, and simple intention more clearly.",
    replyPrompt: "Say I want to go to Japan and I want water.",
    acceptableResponses: ["nihon e ikitai desu", "mizu ga hoshii desu", "にほんへ いきたいです", "みずが ほしいです"],
    modelPrompt: "Model want and reason patterns through goals a beginner genuinely has.",
    guidedPrompt: "Ask the learner what they want and why, then have them answer in short lines.",
    checkpoint: "Learner completes the second grammar-pattern mission.",
    rewardBadge: "Pattern Builder",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-counters",
    title: "Counters",
    missionTitle: "Mission 51: Count the Japanese way",
    objective: "Teach general items, people, books, machines, floors, times, and small animals through English-guided speaking drills.",
    storyHook: "In Japanese, the way you count depends on what you count. This mission makes that system feel usable.",
    checkpointLabel: "Counter mission",
    mode: "speaking",
    demoPhrase: "hitotsu, futatsu, hitori, futari, issatsu, ikkai",
    pattern: "basic counters",
    coverage: ["〜つ", "〜人", "〜冊", "〜台", "〜回", "〜階", "〜歳", "〜匹"],
    outcome: "Learner can answer simple counting prompts more naturally.",
    replyPrompt: "Say one thing, two things, one person, two people, one book, and one time.",
    acceptableResponses: ["hitotsu", "futatsu", "hitori", "futari", "issatsu", "ikkai", "ひとつ"],
    modelPrompt: "Model counters in everyday shopping, people, and schedule situations.",
    guidedPrompt: "Ask how many people, books, or times and let the learner answer in short counter phrases.",
    checkpoint: "Learner clears the counter mission.",
    rewardBadge: "Counter Captain",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-kanji-foundation-1",
    title: "Kanji foundation 1",
    missionTitle: "Mission 52: Read core kanji groups",
    objective: "Teach essential N5 kanji in English by grouping them into numbers, time, and directions before full overload happens.",
    storyHook: "Kanji becomes much less scary when you meet it in useful groups instead of random lists.",
    checkpointLabel: "Kanji group check",
    mode: "listening",
    demoPhrase: "日本, 学生, 先生, 駅, 日, 月, 火, 水",
    pattern: "starter kanji recognition",
    coverage: ["Numbers and money", "Time and dates", "Directions", "Everyday kanji words"],
    outcome: "Learner can recognize and say some of the most important N5 kanji items.",
    replyPrompt: "Read Japan, student, teacher, station, day, month, fire, and water aloud.",
    acceptableResponses: ["nihon", "gakusei", "sensei", "eki", "日", "月", "日本", "学生"],
    modelPrompt: "Model kanji words in useful beginner contexts so symbols arrive with meaning.",
    guidedPrompt: "Ask the learner to read each word and then tell which one means station.",
    checkpoint: "Learner clears the first essential kanji group.",
    rewardBadge: "Kanji Starter",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-kanji-foundation-2",
    title: "Kanji foundation 2",
    missionTitle: "Mission 53: Expand into people, actions, and objects",
    objective: "Continue teaching N5 kanji through people, verbs, and common object categories in spoken English guidance.",
    storyHook: "The next kanji set connects directly to daily life: people, action, and objects you meet often.",
    checkpointLabel: "Kanji group two",
    mode: "listening",
    demoPhrase: "人, 子, 父, 母, 行, 来, 食, 飲, 本, 車",
    pattern: "extended kanji recognition",
    coverage: ["People and family kanji", "Basic action kanji", "Object and environment kanji", "Toward the 103 essential set"],
    outcome: "Learner can recognize more of the essential N5 kanji foundation.",
    replyPrompt: "Read person, child, father, mother, go, come, eat, drink, book, and car aloud.",
    acceptableResponses: ["hito", "ko", "chichi", "haha", "iku", "kuru", "hon", "kuruma"],
    modelPrompt: "Model essential kanji through core words the learner already knows by sound.",
    guidedPrompt: "Ask the learner to read a few kanji items and connect each to a familiar spoken word.",
    checkpoint: "Learner completes the second kanji foundation mission.",
    rewardBadge: "Kanji Builder",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-self-introduction",
    title: "Self introduction",
    missionTitle: "Mission 54: Meet Yuki in Japanese",
    objective: "Teach a complete beginner self-introduction in English and spoken Japanese through a guided roleplay.",
    storyHook: "Yuki meets you for the first time and waits for your introduction. This mission helps you answer warmly and clearly.",
    checkpointLabel: "Self introduction roleplay",
    mode: "roleplay",
    demoPhrase: "hajimemashite. watashi wa Rahul desu. Indo kara kimashita. yoroshiku onegaishimasu.",
    pattern: "first meeting conversation",
    coverage: ["Nice to meet you", "My name is", "I came from", "Job or identity line", "Polite close"],
    outcome: "Learner can introduce themselves in a complete short roleplay.",
    replyPrompt: "Introduce yourself, say where you are from, and end politely.",
    acceptableResponses: ["hajimemashite", "watashi wa rahul desu", "indo kara kimashita", "yoroshiku onegaishimasu"],
    modelPrompt: "Model a complete first-meeting exchange that sounds achievable for a beginner.",
    guidedPrompt: "Roleplay Yuki meeting the learner and ask for name, country, and one identity detail.",
    checkpoint: "Learner clears the self-introduction mission.",
    rewardBadge: "First Conversation Badge",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-cafe-restaurant",
    title: "Cafe and restaurant",
    missionTitle: "Mission 55: Order food with Sakura",
    objective: "Teach the learner to order food and drink politely in English-supported spoken Japanese.",
    storyHook: "Sakura is working behind the counter. This mission teaches you how to ask for water, ramen, and the price.",
    checkpointLabel: "Food roleplay check",
    mode: "roleplay",
    demoPhrase: "sumimasen. mizu o kudasai. raamen o kudasai. kore wa ikura desu ka.",
    pattern: "ordering at a cafe or restaurant",
    coverage: ["Excuse me", "Water please", "Food ordering", "How much is this?", "It is delicious"],
    outcome: "Learner can handle a short food-ordering roleplay.",
    replyPrompt: "Ask for water, ask for ramen, and ask how much it is.",
    acceptableResponses: ["sumimasen", "mizu o kudasai", "raamen o kudasai", "ikura desu ka", "みずをください"],
    modelPrompt: "Model a small but realistic order flow in a Japanese cafe or restaurant.",
    guidedPrompt: "Let Sakura ask what the learner wants and coach them through the order and price question.",
    checkpoint: "Learner completes the cafe mission.",
    rewardBadge: "Food Mission Badge",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-directions",
    title: "Directions",
    missionTitle: "Mission 56: Ask Hiro for the station",
    objective: "Teach the learner to ask for a station and understand basic direction language in a guided roleplay.",
    storyHook: "You are lost for a moment in the city, and Hiro is the helper who can point you toward the station.",
    checkpointLabel: "Direction roleplay check",
    mode: "roleplay",
    demoPhrase: "sumimasen. eki wa doko desu ka. massugu desu. migi desu.",
    pattern: "direction and location conversation",
    coverage: ["Where is the station?", "Straight ahead", "Right", "Thank you", "Polite asking"],
    outcome: "Learner can ask where the station is and respond to a simple direction answer.",
    replyPrompt: "Ask where the station is and say it is on the right.",
    acceptableResponses: ["eki wa doko desu ka", "migi desu", "massugu desu", "えきは どこですか"],
    modelPrompt: "Model a city-help exchange where the learner has one urgent, useful question.",
    guidedPrompt: "Let Hiro answer once, then ask the learner to repeat the direction and the question.",
    checkpoint: "Learner completes the direction mission.",
    rewardBadge: "Direction Master",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-shopping",
    title: "Shopping",
    missionTitle: "Mission 57: Buy something from Tanaka-san",
    objective: "Teach a short shopping conversation in spoken Japanese through English guidance and practical roleplay.",
    storyHook: "Tanaka-san is ready at the shop counter. This mission teaches you to ask the price and make the purchase.",
    checkpointLabel: "Shopping roleplay check",
    mode: "roleplay",
    demoPhrase: "kore wa ikura desu ka. sen en desu. kore o kudasai. kaado wa daijoubu desu ka.",
    pattern: "shopping conversation",
    coverage: ["How much is this?", "It is 1000 yen", "I will take this", "Is card okay?"],
    outcome: "Learner can complete a short shopping exchange with price and payment.",
    replyPrompt: "Ask how much it is, say you will take it, and ask if card is okay.",
    acceptableResponses: ["ikura desu ka", "kore o kudasai", "kaado wa daijoubu desu ka", "これをください"],
    modelPrompt: "Model a natural shop counter exchange that feels directly useful to a traveler.",
    guidedPrompt: "Let Tanaka-san offer the price and ask the learner to complete the purchase politely.",
    checkpoint: "Learner clears the shopping mission.",
    rewardBadge: "Shopping Samurai",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-daily-routine",
    title: "Daily routine",
    missionTitle: "Mission 58: Describe your day in Japanese",
    objective: "Teach the learner to talk about waking up, eating breakfast, and studying through a simple routine conversation.",
    storyHook: "Real language lives in daily habits. This mission helps you describe what your day actually looks like.",
    checkpointLabel: "Routine roleplay check",
    mode: "speaking",
    demoPhrase: "rokuji ni okimasu. asagohan o tabemasu. nihongo o benkyou shimasu.",
    pattern: "daily routine conversation",
    coverage: ["Wake-up time", "Breakfast", "Study routine", "Simple habit sequence"],
    outcome: "Learner can speak about a basic daily routine in short lines.",
    replyPrompt: "Say what time you wake up, that you eat breakfast, and that you study Japanese.",
    acceptableResponses: ["rokuji ni okimasu", "asagohan o tabemasu", "nihongo o benkyou shimasu", "ろくじに おきます"],
    modelPrompt: "Model a short morning routine that feels realistic and achievable.",
    guidedPrompt: "Ask the learner for the time they wake up and one or two daily actions.",
    checkpoint: "Learner completes the daily routine mission.",
    rewardBadge: "Daily Flow Badge",
    rewardXp: 15,
  }),
  createJapaneseSeed({
    id: "n5-listening-practice",
    title: "Listening practice",
    missionTitle: "Mission 59: Train your ear for N5 Japanese",
    objective: "Cover the listening side of the course with guided phrase, number, word, and mini-conversation listening tasks explained in English.",
    storyHook: "Now the language must arrive through your ears, not just your eyes. This mission turns hearing into a real skill.",
    checkpointLabel: "Listening challenge",
    mode: "listening",
    demoPhrase: "arigatou gozaimasu. rokuji. mizu o kudasai. kore wa hon desu.",
    pattern: "mixed listening review",
    coverage: ["Vowels", "Kana sounds", "Words", "Numbers", "Sentences", "Mini conversations"],
    outcome: "Learner can catch beginner Japanese by ear with more confidence.",
    replyPrompt: "Repeat what you hear and answer one small listening prompt.",
    acceptableResponses: ["arigatou gozaimasu", "rokuji", "mizu o kudasai", "ありがとうございます"],
    modelPrompt: "Model small listening moments across the whole N5 course, keeping the learner active rather than passive.",
    guidedPrompt: "Ask the learner to hear, repeat, and then answer one small meaning or response question.",
    checkpoint: "Learner clears the listening practice mission.",
    rewardBadge: "Listening Ladder",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-speaking-practice",
    title: "Speaking practice",
    missionTitle: "Mission 60: Speak across the whole N5 path",
    objective: "Pull together vowels, kana, words, roleplays, and AI question answering into a broad speaking mission.",
    storyHook: "This is where all the pieces begin acting like one real language instead of separate study topics.",
    checkpointLabel: "Speaking challenge",
    mode: "checkpoint",
    demoPhrase: "watashi wa Rahul desu. mizu o kudasai. eki wa doko desu ka.",
    pattern: "integrated speaking review",
    coverage: ["Repeat sounds", "Read words aloud", "Introduce yourself", "Order food", "Ask directions", "Answer AI prompts"],
    outcome: "Learner can use Japanese across several beginner situations in one session.",
    replyPrompt: "Introduce yourself, order one thing, and ask for the station.",
    acceptableResponses: ["watashi wa rahul desu", "mizu o kudasai", "eki wa doko desu ka", "わたしは ラフルです"],
    modelPrompt: "Model a broad but learner-safe speaking loop that proves the course is becoming real skill.",
    guidedPrompt: "Ask three practical prompts in sequence and coach the learner through one smoother retry.",
    checkpoint: "Learner clears the integrated speaking mission.",
    rewardBadge: "Speaking Climber",
    rewardXp: 25,
  }),
  createJapaneseSeed({
    id: "n5-reading-practice",
    title: "Reading practice",
    missionTitle: "Mission 61: Climb the N5 reading ladder",
    objective: "Review the full reading path from single hiragana through short paragraphs using English support and voice output.",
    storyHook: "You started with one row of sounds, and now you can read full beginner lines. This mission proves that growth clearly.",
    checkpointLabel: "Reading ladder challenge",
    mode: "listening",
    demoPhrase: "あ, ねこ, ホテル, 日本, これは ほんです。 わたしは ラフルです。",
    pattern: "integrated reading review",
    coverage: ["Single hiragana", "Hiragana words", "Katakana words", "Kanji words", "Short sentences", "Tiny paragraph"],
    outcome: "Learner can read across the full beginner script ladder with stronger calm.",
    replyPrompt: "Read one symbol, one word, one katakana word, one kanji word, and one short sentence aloud.",
    acceptableResponses: ["あ", "ねこ", "ホテル", "日本", "これは ほんです"],
    modelPrompt: "Model the full reading ladder from simplest to richest so the learner hears how far they have come.",
    guidedPrompt: "Ask the learner to climb the ladder one piece at a time and retry the hardest rung once.",
    checkpoint: "Learner completes the reading ladder mission.",
    rewardBadge: "Reading Ranger",
    rewardXp: 20,
  }),
  createJapaneseSeed({
    id: "n5-review-and-final-exam",
    title: "Review and final N5 certificate exam",
    missionTitle: "Final Mission: Clear the N5 challenge",
    objective: "Review the full course and run the final integrated N5 certificate exam in English-guided spoken Japanese.",
    storyHook: "Everything now comes together: sounds, kana, words, grammar, reading, listening, and practical roleplay. This is the final gate.",
    checkpointLabel: "N5 certificate gate",
    mode: "checkpoint",
    demoPhrase: "hajimemashite. watashi wa Rahul desu. mizu o kudasai. eki wa doko desu ka.",
    pattern: "final N5 exam",
    coverage: ["Sounds", "Hiragana", "Katakana", "Numbers", "Vocabulary", "Particles", "Verb forms", "Adjectives", "Grammar", "Counters", "Kanji", "Listening", "Reading", "Speaking roleplays"],
    outcome: "Learner proves they can finish the platform N5 journey and qualify for the certificate.",
    replyPrompt: "Complete the guided exam with a greeting, self-introduction, practical request, and direction question.",
    acceptableResponses: ["hajimemashite", "watashi wa rahul desu", "mizu o kudasai", "eki wa doko desu ka", "はじめまして"],
    modelPrompt: "Model the full final mission once so the learner hears the target level for certificate completion.",
    guidedPrompt: "Run a compact but real N5 review and final speaking loop that touches the major beginner systems.",
    checkpoint: "Mark the learner complete only after they clear the final integrated N5 journey.",
    rewardBadge: "N5 Champion",
    rewardXp: 100,
  }),
];
