import { type ExamQuestion } from "@/lib/course-types";

function question(
  id: string,
  sectionId: string,
  skillFocus: string,
  prompt: string,
  questionType: string,
  correctAnswer: string,
  explanation: string,
  choices: string[] = [],
): ExamQuestion {
  return {
    choices,
    correctAnswer,
    explanation,
    id,
    prompt,
    questionType,
    sectionId,
    skillFocus,
  };
}

export const japaneseQuestionBankC = [
  question(
    "n5-counters-2",
    "counters",
    "General item counting",
    "Count three small objects using the general counter.",
    "spoken response",
    "みっつ",
    "The learner should know the native-style item counters for common small quantities.",
  ),
  question(
    "n5-counters-3",
    "counters",
    "Age expression",
    "How would you say 'I am 20 years old'?",
    "spoken response",
    "はたちです",
    "Age is a classic N5 speaking topic, and twenty has a special form worth practicing.",
  ),
  question(
    "n5-kanji-1",
    "kanji",
    "Basic kanji reading",
    "Read this word aloud: 日本",
    "spoken response",
    "にほん",
    "This checks whether the learner can read one of the most common N5 kanji compounds naturally.",
  ),
  question(
    "n5-kanji-2",
    "kanji",
    "Meaning recognition",
    "Which kanji means 'person'?",
    "multiple choice",
    "人",
    "人 appears across family, counting, jobs, and identity expressions throughout N5 content.",
    ["日", "人", "月"],
  ),
  question(
    "n5-kanji-3",
    "kanji",
    "Useful place word",
    "What is the reading of 学校?",
    "short answer",
    "がっこう",
    "This is one of the most useful N5 location words and combines a small pause sound with kanji recognition.",
  ),
  question(
    "n5-listening-1",
    "listening",
    "Number listening",
    "You hear さんびゃくえん. What did the speaker say?",
    "short answer",
    "300 yen",
    "The learner should connect heard Japanese number language to a practical shopping meaning quickly.",
  ),
  question(
    "n5-listening-2",
    "listening",
    "Greeting recognition",
    "If the tutor says こんばんは, what situation is most likely?",
    "multiple choice",
    "An evening greeting",
    "Listening tasks should train context recognition, not only literal translation.",
    ["A morning greeting", "An evening greeting", "A farewell at school"],
  ),
  question(
    "n5-listening-3",
    "listening",
    "Question response",
    "You hear おなまえは？ What is the speaker asking?",
    "short answer",
    "What is your name?",
    "The learner should react to core conversation questions immediately during live speaking.",
  ),
  question(
    "n5-reading-1",
    "reading",
    "Short sentence reading",
    "Read and understand: わたしは えきへ いきます。",
    "short answer",
    "I am going to the station.",
    "The sentence combines topic marking, destination marking, and a high-frequency place noun.",
  ),
  question(
    "n5-reading-2",
    "reading",
    "Tiny paragraph meaning",
    "A card says: きょうは にちようびです。 What key information should you understand?",
    "short answer",
    "Today is Sunday.",
    "This is exactly the level of calm, useful comprehension we want from beginner reading work.",
  ),
  question(
    "n5-reading-3",
    "reading",
    "Mixed-script recognition",
    "Which reading matches スーパー?",
    "multiple choice",
    "suupaa",
    "Katakana reading confidence is necessary because everyday Japanese signage uses borrowed words constantly.",
    ["suupaa", "shuupaa", "sopaa"],
  ),
  question(
    "n5-speaking-1",
    "speaking",
    "Self introduction",
    "Give a short introduction with your name and nationality.",
    "guided response",
    "わたしは ___ です。___ から きました。",
    "This is one of the best integrated N5 speaking tasks because it combines identity, grammar, and clear pacing.",
  ),
  question(
    "n5-speaking-2",
    "speaking",
    "Ordering food",
    "Say: 'One coffee, please.'",
    "spoken response",
    "コーヒーを ひとつ ください",
    "The learner should combine the object marker, counter, and request pattern in one polite cafe line.",
  ),
  question(
    "n5-speaking-3",
    "speaking",
    "Asking for direction help",
    "How would you ask 'Where is the station?'",
    "spoken response",
    "えきは どこですか",
    "This is a compact, high-value survival question for travel and daily speaking confidence.",
  ),
] as const;
