import { type KanjiGroup } from "@/lib/course-types";

type KanjiRow = [string, string, string, string];

function group(id: string, title: string, entries: KanjiRow[]): KanjiGroup {
  return {
    entries: entries.map(([japanese, reading, meaning, example], index) => ({
      example,
      id: `${id}-${index + 1}`,
      japanese,
      meaning,
      reading,
      sortOrder: index + 1,
    })),
    id,
    title,
  };
}

export const japaneseKanjiBank = [
  group("kanji-numbers-money", "Numbers and Money", [
    ["一", "ichi", "one", "一つ"],
    ["二", "ni", "two", "二つ"],
    ["三", "san", "three", "三人"],
    ["四", "yon / shi", "four", "四時"],
    ["五", "go", "five", "五日"],
    ["六", "roku", "six", "六時"],
    ["七", "nana / shichi", "seven", "七人"],
    ["八", "hachi", "eight", "八百"],
    ["九", "kyuu / ku", "nine", "九時"],
    ["十", "juu", "ten", "十円"],
    ["百", "hyaku", "hundred", "百円"],
    ["千", "sen", "thousand", "千円"],
    ["万", "man", "ten thousand", "一万円"],
    ["円", "en", "yen / circle", "五百円"],
  ]),
  group("kanji-time-nature", "Time, Dates, and Nature", [
    ["日", "nichi / hi", "day / sun", "日本"],
    ["月", "getsu / tsuki", "month / moon", "月曜日"],
    ["火", "ka / hi", "fire", "火曜日"],
    ["水", "sui / mizu", "water", "水曜日"],
    ["木", "moku / ki", "tree / wood", "木曜日"],
    ["金", "kin / kane", "gold / money", "金曜日"],
    ["土", "do / tsuchi", "earth / soil", "土曜日"],
    ["年", "nen / toshi", "year", "一年"],
    ["時", "ji / toki", "time / hour", "六時"],
    ["分", "fun / bun", "minute / divide", "十分"],
    ["半", "han", "half", "三時半"],
    ["今", "ima / kon", "now", "今"],
    ["週", "shuu", "week", "今週"],
    ["午", "go", "noon", "午後"],
    ["毎", "mai", "every", "毎日"],
    ["曜", "you", "day of week", "月曜日"],
    ["天", "ten / ame", "heaven / sky", "天気"],
    ["気", "ki", "spirit / energy", "元気"],
    ["空", "sora / kuu", "sky / empty", "空"],
    ["雨", "ame / u", "rain", "雨"],
    ["電", "den", "electricity", "電話"],
  ]),
  group("kanji-directions-places", "Directions, Size, and Locations", [
    ["上", "ue / jou", "up / above", "上"],
    ["下", "shita / ka", "down / below", "下"],
    ["左", "hidari / sa", "left", "左"],
    ["右", "migi / u", "right", "右"],
    ["前", "mae / zen", "front / before", "前"],
    ["後", "ushiro / go", "back / behind", "後"],
    ["中", "naka / chuu", "inside / middle", "中"],
    ["外", "soto / gai", "outside", "外"],
    ["北", "kita / hoku", "north", "北"],
    ["南", "minami / nan", "south", "南"],
    ["東", "higashi / tou", "east", "東京"],
    ["西", "nishi / sei", "west", "西"],
    ["大", "oo / dai", "big", "大学"],
    ["小", "chiisai / shou", "small", "小さい"],
    ["高", "takai / kou", "high / expensive", "高校"],
    ["長", "nagai / chou", "long / leader", "校長"],
    ["多", "ooi / ta", "many / much", "多い"],
    ["少", "sukunai / shou", "few / little", "少し"],
    ["国", "kuni / koku", "country", "中国"],
    ["駅", "eki", "station", "駅"],
    ["道", "michi / dou", "road / path", "道"],
    ["校", "kou", "school", "学校"],
    ["店", "mise / ten", "shop / store", "店"],
  ]),
  group("kanji-people-relations", "People and Relationships", [
    ["人", "hito / jin", "person", "日本人"],
    ["子", "ko / shi", "child", "子ども"],
    ["学", "gaku / manabu", "study", "学生"],
    ["父", "chichi / fu", "father", "父"],
    ["母", "haha / bo", "mother", "母"],
    ["友", "tomo / yuu", "friend", "友だち"],
    ["女", "onna / jo", "woman", "女"],
    ["男", "otoko / dan", "man", "男"],
    ["先", "saki / sen", "ahead / before", "先生"],
    ["生", "sei / ikiru", "life / birth", "学生"],
    ["名", "na / mei", "name", "名前"],
  ]),
  group("kanji-actions", "Basic Actions and Verbs", [
    ["行", "iku / kou", "to go", "行きます"],
    ["来", "kuru / rai", "to come", "来ます"],
    ["出", "deru / shutsu", "to exit / go out", "出ます"],
    ["入", "hairu / nyuu", "to enter", "入ります"],
    ["食", "taberu / shoku", "to eat", "食べます"],
    ["飲", "nomu / in", "to drink", "飲みます"],
    ["見", "miru / ken", "to see / watch", "見ます"],
    ["聞", "kiku / bun", "to hear / listen", "聞きます"],
    ["書", "kaku / sho", "to write", "書きます"],
    ["話", "hanasu / wa", "to speak / talk", "話します"],
    ["読", "yomu / doku", "to read", "読みます"],
    ["買", "kau / bai", "to buy", "買います"],
    ["立", "tatsu / ritsu", "to stand", "立ちます"],
    ["会", "au / kai", "to meet", "会います"],
    ["休", "yasumu / kyuu", "to rest", "休みます"],
    ["言", "iu / gen", "to say", "言います"],
    ["思", "omou / shi", "to think", "思います"],
    ["社", "sha / yashiro", "company or shrine", "会社"],
    ["作", "tsukuru / saku", "to make", "作ります"],
    ["使", "tsukau / shi", "to use", "使います"],
    ["知", "shiru / chi", "to know", "知っています"],
    ["住", "sumu / juu", "to reside / live", "住んでいます"],
  ]),
  group("kanji-objects-environment", "Environment and Objects", [
    ["山", "yama / san", "mountain", "山"],
    ["川", "kawa / sen", "river", "川"],
    ["本", "hon", "book / source", "本"],
    ["車", "kuruma / sha", "car / vehicle", "車"],
    ["語", "go / kataru", "language", "日本語"],
    ["何", "nani / ka", "what", "何ですか"],
    ["物", "mono / butsu", "thing", "食べ物"],
    ["間", "aida / kan", "between / interval", "時間"],
    ["白", "shiro / haku", "white", "白い"],
    ["新", "atarashii / shin", "new", "新しい"],
    ["古", "furui / ko", "old", "古い"],
    ["足", "ashi / soku", "leg / foot", "足"],
  ]),
] as const;
