import { type ExamQuestion } from "@/lib/course-types";

function question(
  id: string,
  sectionId: string,
  skillFocus: string,
  prompt: string,
  questionType: string,
  correctAnswer: string,
  explanation: string,
  choices: string[] = [],
): ExamQuestion {
  return {
    choices,
    correctAnswer,
    explanation,
    id,
    prompt,
    questionType,
    sectionId,
    skillFocus,
  };
}

export const japaneseQuestionBankB = [
  question(
    "n5-numbers-3",
    "numbers",
    "Money use",
    "How would you answer 'How much is it?' if the price is 500 yen?",
    "spoken response",
    "go hyaku en desu",
    "Practical money answers should come out as one smooth phrase, not as isolated number words.",
  ),
  question(
    "n5-vocab-1",
    "vocabulary",
    "Daily greeting use",
    "What do you say to someone in the morning?",
    "short answer",
    "ohayou gozaimasu",
    "This is one of the highest-frequency polite expressions in beginner Japanese.",
  ),
  question(
    "n5-vocab-2",
    "vocabulary",
    "Everyday object recall",
    "Which word means 'water'?",
    "multiple choice",
    "みず",
    "Core everyday nouns should become fast retrieval items in N5 speaking.",
    ["ほん", "みず", "えき"],
  ),
  question(
    "n5-vocab-3",
    "vocabulary",
    "Self-introduction language",
    "Say the Japanese word for 'student'.",
    "spoken response",
    "gakusei",
    "This word appears constantly in first conversations and classroom-style roleplay.",
  ),
  question(
    "n5-particle-1",
    "particles",
    "Topic marking",
    "Choose the correct particle: わたし ___ ラフルです。",
    "multiple choice",
    "は",
    "は marks the topic of the sentence in this basic self-introduction pattern.",
    ["を", "は", "で"],
  ),
  question(
    "n5-particle-2",
    "particles",
    "Object marking",
    "Complete the line: パン ___ たべます。",
    "short answer",
    "を",
    "を marks the direct object, so it links the food being eaten to the verb.",
  ),
  question(
    "n5-particle-3",
    "particles",
    "Place of action",
    "Which particle fits: がっこう ___ べんきょうします。",
    "multiple choice",
    "で",
    "で marks the place where an action happens.",
    ["に", "で", "と"],
  ),
  question(
    "n5-verbs-1",
    "verbs-adjectives",
    "Polite negative",
    "Change たべます into the polite negative form.",
    "short answer",
    "たべません",
    "The learner should be able to move from polite affirmative into polite negative quickly.",
  ),
  question(
    "n5-verbs-2",
    "verbs-adjectives",
    "Past tense",
    "What is the past polite form of いきます?",
    "short answer",
    "いきました",
    "This is a core N5 conjugation used constantly in past-experience sentences.",
  ),
  question(
    "n5-verbs-3",
    "verbs-adjectives",
    "Adjective distinction",
    "Which one is a な-adjective?",
    "multiple choice",
    "しずか",
    "しずか is a classic beginner な-adjective, unlike い-adjectives such as おおきい.",
    ["おおきい", "しずか", "あたらしい"],
  ),
  question(
    "n5-grammar-1",
    "grammar",
    "Permission pattern",
    "How do you say 'May I sit here?' using てもいいですか?",
    "spoken response",
    "ここに すわっても いいですか",
    "The learner should connect the te-form to a practical permission request.",
  ),
  question(
    "n5-grammar-2",
    "grammar",
    "Request pattern",
    "Fill in the pattern: もういちど いって ___。",
    "short answer",
    "ください",
    "てください is one of the most useful N5 request forms and should feel automatic.",
  ),
  question(
    "n5-grammar-3",
    "grammar",
    "Desire expression",
    "Choose the best completion: みずが ___ です。",
    "multiple choice",
    "ほしい",
    "ほしい expresses wanting a thing, which makes it different from たい for wanting to do an action.",
    ["たべたい", "ほしい", "じょうず"],
  ),
  question(
    "n5-counters-1",
    "counters",
    "People counting",
    "How do you say 'two people'?",
    "short answer",
    "ふたり",
    "This is an irregular but extremely common counter form and should be memorized early.",
  ),
] as const;
