import { createJapaneseSeed } from "@/lib/japanese-seed";

export const japaneseN5Journey = [
  createJapaneseSeed({
    id: "n5-kanji-foundation",
    title: "Kanji foundation",
    missionTitle: "Mission 23: Enter beginner kanji safely",
    objective: "Introduce the essential N5 kanji in meaning-rich groups after kana is already comfortable.",
    storyHook: "You have earned the right to meet kanji without fear. This mission starts with the core symbols that appear everywhere in N5 life.",
    checkpointLabel: "Kanji starter check",
    mode: "listening",
    demoPhrase: "日本, 学生, 先生, 駅",
    pattern: "starter kanji recognition",
    coverage: ["103 essential kanji", "Numbers and money", "Time and dates", "Directions", "People", "Basic actions", "Common objects"],
    outcome: "Learner can recognize and say a few core N5 kanji words instead of fearing all kanji at once.",
    replyPrompt: "Read Japan, student, teacher, and station aloud.",
    rewardBadge: "Kanji Starter",
    rewardXp: 25,
    acceptableResponses: ["nihon", "gakusei", "sensei", "eki", "日本", "学生", "先生", "駅"],
    modelPrompt: "Model beginner kanji words as complete useful vocabulary, not isolated symbols with no life.",
    guidedPrompt: "Ask the learner to read each word and connect it to its meaning in one short step.",
    checkpoint: "The learner reads four essential kanji words with usable confidence.",
  }),
  createJapaneseSeed({
    id: "n5-self-introduction",
    title: "Self introduction",
    missionTitle: "Mission 24: Introduce yourself with confidence",
    objective: "Turn the learner's first Japanese identity lines into a complete beginner conversation mission.",
    storyHook: "You meet Yuki for the first time. This mission helps you say your name, where you are from, and who you are without panic.",
    checkpointLabel: "Introduction roleplay check",
    mode: "roleplay",
    demoPhrase: "hajimemashite, watashi wa Rahul desu. Indo kara kimashita.",
    pattern: "meeting someone for the first time",
    coverage: ["Nice to meet you", "My name is...", "I came from...", "Occupation line", "Polite close"],
    outcome: "Learner can introduce themselves with name, origin, and polite close.",
    replyPrompt: "Introduce yourself, say where you are from, and finish politely.",
    rewardBadge: "First Conversation Badge",
    rewardXp: 20,
    acceptableResponses: ["hajimemashite", "watashi wa rahul desu", "indo kara kimashita", "よろしくおねがいします"],
    modelPrompt: "Model a full first-meeting exchange that sounds warm, respectful, and beginner-safe.",
    guidedPrompt: "Roleplay meeting Yuki for the first time and ask the learner to share name and country.",
    checkpoint: "The learner completes a first self-introduction from start to finish.",
  }),
  createJapaneseSeed({
    id: "n5-cafe-restaurant",
    title: "Cafe and restaurant",
    missionTitle: "Mission 25: Order food in Japanese",
    objective: "Make Japanese feel exciting and useful through food ordering and polite restaurant phrases.",
    storyHook: "Sakura waits at the café counter. This mission teaches you how to ask for water, ramen, and the bill without switching to English.",
    checkpointLabel: "Food mission check",
    mode: "roleplay",
    demoPhrase: "mizu o kudasai. raamen o kudasai.",
    pattern: "ordering food and drinks",
    coverage: ["Excuse me", "Water please", "Food ordering", "How much is this?", "It is delicious"],
    outcome: "Learner can order a drink or dish and ask a price politely.",
    replyPrompt: "Ask for water and ramen, then ask how much it is.",
    rewardBadge: "Food Mission Badge",
    rewardXp: 20,
    acceptableResponses: ["mizu o kudasai", "raamen o kudasai", "ikura desu ka", "みずをください", "ラーメンをください"],
    modelPrompt: "Model a tiny cafe interaction with Sakura so the learner hears how useful polite Japanese already sounds.",
    guidedPrompt: "Ask the learner to order a drink, then a meal, then ask the cost once.",
    checkpoint: "The learner completes one food-ordering roleplay with clear intent.",
  }),
  createJapaneseSeed({
    id: "n5-directions",
    title: "Directions",
    missionTitle: "Mission 26: Find your way to the station",
    objective: "Teach the learner to ask where places are and understand very basic direction replies.",
    storyHook: "You are standing on a Tokyo street corner and need the station fast. This mission teaches the questions that save the day.",
    checkpointLabel: "Direction mission check",
    mode: "roleplay",
    demoPhrase: "eki wa doko desu ka. migi desu.",
    pattern: "asking and answering where something is",
    coverage: ["Where is...?", "Straight ahead", "Right and left", "Station vocabulary", "Thank-you close"],
    outcome: "Learner can ask for the station and understand a short direction answer.",
    replyPrompt: "Ask where the station is, then say it is on the right.",
    rewardBadge: "Direction Master",
    rewardXp: 20,
    acceptableResponses: ["eki wa doko desu ka", "migi desu", "えきは どこですか", "みぎです"],
    modelPrompt: "Model a station-help moment with Hiro so the learner hears direction Japanese in a real travel scene.",
    guidedPrompt: "Ask the learner for the station question first, then have them answer a direction prompt.",
    checkpoint: "The learner manages one ask-for-directions exchange aloud.",
  }),
  createJapaneseSeed({
    id: "n5-shopping",
    title: "Shopping",
    missionTitle: "Mission 27: Buy something with confidence",
    objective: "Prepare the learner for a simple store interaction with prices, choice, and payment language.",
    storyHook: "Tanaka-san has what you need in the shop, but now you must ask the price and choose politely like a real customer.",
    checkpointLabel: "Shopping mission check",
    mode: "roleplay",
    demoPhrase: "kore o kudasai. kaado wa daijoubu desu ka.",
    pattern: "shopping and payment phrases",
    coverage: ["How much is this?", "I'll take this", "Card okay?", "Simple payment language", "Shop counter rhythm"],
    outcome: "Learner can choose an item, ask the price, and confirm payment politely.",
    replyPrompt: "Say I will take this and ask if card is okay.",
    rewardBadge: "Shopping Samurai",
    rewardXp: 20,
    acceptableResponses: ["kore o kudasai", "kaado wa daijoubu desu ka", "これをください", "カードは だいじょうぶですか"],
    modelPrompt: "Model a short shop counter exchange with Tanaka-san so the learner gets a complete micro-scene.",
    guidedPrompt: "Have the learner select an item, ask the price, then confirm card payment.",
    checkpoint: "The learner clears one full shopping mini-roleplay.",
  }),
  createJapaneseSeed({
    id: "n5-daily-routine",
    title: "Daily routine",
    missionTitle: "Mission 28: Talk about your day",
    objective: "Help the learner talk about waking up, eating, and studying so Japanese starts entering everyday life.",
    storyHook: "Japanese becomes real when you can describe your own life. This mission brings time, actions, and habits together.",
    checkpointLabel: "Routine check",
    mode: "speaking",
    demoPhrase: "rokuji ni okimasu. nihongo o benkyou shimasu.",
    pattern: "time plus daily action",
    coverage: ["Wake-up time", "Breakfast", "Study routines", "Simple daily habit sentences"],
    outcome: "Learner can describe one or two parts of a simple daily routine.",
    replyPrompt: "Say what time you wake up and that you study Japanese.",
    rewardBadge: "Daily Flow Badge",
    rewardXp: 15,
    acceptableResponses: ["rokuji ni okimasu", "nihongo o benkyou shimasu", "ろくじに おきます", "にほんごを べんきょうします"],
    modelPrompt: "Model one clean morning routine answer and one study habit line.",
    guidedPrompt: "Ask the learner what time they wake up and what they study, then retry the more difficult line.",
    checkpoint: "The learner gives two short routine answers clearly.",
  }),
  createJapaneseSeed({
    id: "n5-listening-practice",
    title: "Listening practice",
    missionTitle: "Mission 29: Train your Japanese ear",
    objective: "Train the learner to recognize sounds, words, numbers, and mini conversations by ear.",
    storyHook: "Now the challenge is no longer just saying Japanese. It is catching it in the air before the text appears.",
    checkpointLabel: "Listening challenge check",
    mode: "listening",
    demoPhrase: "arigatou gozaimasu. rokuji. mizu o kudasai.",
    pattern: "ear training across core N5 material",
    coverage: ["Sound selection", "Kana recognition", "Word meaning by ear", "Number hearing", "Mini conversations", "Listening answers"],
    outcome: "Learner can react to beginner Japanese without waiting for heavy visual support.",
    replyPrompt: "Repeat what you hear, then answer the small listening prompt.",
    rewardBadge: "Listening Ladder",
    rewardXp: 20,
    acceptableResponses: ["arigatou gozaimasu", "rokuji", "mizu o kudasai", "ありがとうございます", "ろくじ"],
    modelPrompt: "Play short N5 phrases naturally and teach the learner to catch meaning from rhythm and keywords.",
    guidedPrompt: "Run a sequence of tiny listening tasks: phrase, number, and mini conversation response.",
    checkpoint: "The learner completes a mixed listening pass across core N5 content.",
  }),
  createJapaneseSeed({
    id: "n5-speaking-practice",
    title: "Speaking practice",
    missionTitle: "Mission 30: Speak across real beginner situations",
    objective: "Push the learner from repetition into active voice answers, roleplay turns, and beginner confidence.",
    storyHook: "This is where all the earlier drills become real speech. You now answer, request, and roleplay like a true N5 beginner speaker.",
    checkpointLabel: "Speaking badge check",
    mode: "checkpoint",
    demoPhrase: "watashi wa Rahul desu. mizu o kudasai. eki wa doko desu ka.",
    pattern: "guided speaking across N5 tasks",
    coverage: ["Repeat sounds", "Read words aloud", "Answer AI prompts", "Introduce yourself", "Order food", "Ask directions", "Roleplay completion"],
    outcome: "Learner can respond across self-introduction, food, and direction prompts in one session.",
    replyPrompt: "Introduce yourself, order one item, and ask for the station.",
    rewardBadge: "Speaking Climber",
    rewardXp: 25,
    acceptableResponses: ["watashi wa rahul desu", "mizu o kudasai", "eki wa doko desu ka", "わたしは ラフルです"],
    modelPrompt: "Model a compact speaking mission that mixes several N5 situations without overwhelming the learner.",
    guidedPrompt: "Ask three practical prompts in sequence and coach for smoother flow between them.",
    checkpoint: "The learner completes a multi-part speaking loop with visible improvement.",
  }),
  createJapaneseSeed({
    id: "n5-reading-practice",
    title: "Reading practice",
    missionTitle: "Mission 31: Climb the N5 reading ladder",
    objective: "Blend kana, katakana, kanji words, and short sentences into a reading ladder the learner can actually enjoy.",
    storyHook: "What began with aiueo now becomes full Japanese lines. This mission proves you can read across the whole beginner spectrum.",
    checkpointLabel: "Reading ladder check",
    mode: "listening",
    demoPhrase: "ねこ, ホテル, 日本, これは ほんです。",
    pattern: "reading from single words to short sentences",
    coverage: ["Single hiragana", "Hiragana words", "Katakana words", "Kanji words", "Short sentences", "Tiny paragraphs"],
    outcome: "Learner can read short N5 material with more calm and less decoding panic.",
    replyPrompt: "Read the hiragana word, katakana word, kanji word, and short sentence aloud.",
    rewardBadge: "Reading Ranger",
    rewardXp: 20,
    acceptableResponses: ["neko", "hoteru", "nihon", "kore wa hon desu", "ねこ", "ホテル", "日本"],
    modelPrompt: "Model a reading ladder that moves from one-word wins into the first short sentence victory.",
    guidedPrompt: "Ask the learner to climb the reading ladder one item at a time and repeat the hardest rung once.",
    checkpoint: "The learner clears four reading stages from simple word to short sentence.",
  }),
  createJapaneseSeed({
    id: "n5-final-exam",
    title: "Final N5 certificate exam",
    missionTitle: "Final Mission: Clear the N5 challenge",
    objective: "Run the final guided N5 voice exam across sounds, kana, numbers, core phrases, reading, and speaking.",
    storyHook: "You have unlocked every major beginner skill. This final mission pulls the whole Japan journey together and earns the certificate.",
    checkpointLabel: "N5 certificate gate",
    mode: "checkpoint",
    demoPhrase: "hajimemashite. watashi wa Rahul desu. mizu o kudasai. eki wa doko desu ka.",
    pattern: "final integrated N5 speaking and listening check",
    coverage: ["Sounds and kana", "Numbers", "Vocabulary", "Particles", "Verb and adjective use", "Grammar patterns", "Counters", "Kanji", "Listening", "Reading", "Speaking roleplays"],
    outcome: "Learner proves they can complete the platform's N5 beginner journey and qualify for the certificate.",
    replyPrompt: "Complete the guided exam with a greeting, self-introduction, practical request, and direction question.",
    rewardBadge: "N5 Champion",
    rewardXp: 100,
    acceptableResponses: ["hajimemashite", "watashi wa rahul desu", "mizu o kudasai", "eki wa doko desu ka", "はじめまして"],
    modelPrompt: "Model the full final mission once so the learner hears the target quality for a certificate-level attempt.",
    guidedPrompt: "Run a compact exam touching sound control, reading, listening, and practical speaking before marking completion.",
    checkpoint: "Only mark this mission complete when the learner can finish the final guided N5 loop with clear effort.",
  }),
];
