import { createJapaneseSeed } from "@/lib/japanese-seed";

export const japaneseN5Foundations = [
  createJapaneseSeed({
    id: "n5-what-is-japanese",
    title: "What is Japanese?",
    missionTitle: "Mission 1: Land in Japan with a clear map",
    objective: "Open the course with a calm beginner-safe map of Japanese, the writing systems, and the N5 mission ahead.",
    storyHook: "You have just landed in Tokyo and every sign feels mysterious. This mission shows you what Japanese is made of before you try to speak it.",
    checkpointLabel: "Course orientation mission",
    mode: "listening",
    demoPhrase: "nihongo, hiragana, katakana, kanji",
    pattern: "course orientation and writing-system awareness",
    coverage: ["What Japanese is", "How Japanese differs from English", "Hiragana", "Katakana", "Kanji", "JLPT N5"],
    outcome: "Learner understands what Japanese uses instead of ABCD and feels safe starting from zero.",
    replyPrompt: "Say nihongo and name one Japanese writing system aloud.",
    rewardBadge: "First Step in Japan",
    rewardXp: 10,
    acceptableResponses: ["nihongo", "hiragana", "katakana", "kanji", "にほんご", "ひらがな"],
    modelPrompt: "Start with a first-arrival-in-Japan story and explain that Japanese will unlock one layer at a time.",
    guidedPrompt: "Ask the learner what they noticed about Japanese, then have them repeat the core system words once clearly.",
    checkpoint: "Finish when the learner can say nihongo and identify at least one writing system.",
  }),
  createJapaneseSeed({
    id: "n5-romaji-bridge",
    title: "Romaji bridge",
    missionTitle: "Mission 2: Cross the romaji bridge",
    objective: "Use English-letter support as a bridge so absolute beginners can pronounce Japanese before reading kana.",
    storyHook: "You spot sushi, nihon, and arigatou written in English letters first. This mission teaches you how those spellings guide your ear into real Japanese.",
    checkpointLabel: "Romaji bridge check",
    mode: "repeat",
    demoPhrase: "sushi, arigatou, nihon",
    pattern: "romaji to spoken Japanese",
    coverage: ["What romaji is", "Japanese vowels in romaji", "Consonant sounds", "Reading starter words", "Bridge to hiragana"],
    outcome: "Learner can use romaji support without depending on it as the final destination.",
    replyPrompt: "Read the romaji words aloud with calm Japanese rhythm.",
    rewardBadge: "Romaji Bridge Badge",
    rewardXp: 15,
    acceptableResponses: ["sushi", "arigatou", "nihon", "すし", "ありがとう", "にほん"],
    modelPrompt: "Model familiar romaji words and show how they point toward real Japanese pronunciation, not English stress.",
    guidedPrompt: "Have the learner read a romaji word, then repeat it once with cleaner Japanese timing.",
    checkpoint: "Confirm the learner understands romaji is a bridge and can speak three starter words aloud.",
  }),
  createJapaneseSeed({
    id: "n5-vowels",
    title: "Japanese vowels",
    missionTitle: "Mission 3: Hear the five Japanese vowels",
    objective: "Build the five core Japanese vowel sounds so later words sound clean instead of guessed from English.",
    storyHook: "Before words, you need the five sounds that power almost everything in beginner Japanese. This is where your mouth and ear reset.",
    checkpointLabel: "Vowel mission check",
    mode: "repeat",
    demoPhrase: "a, i, u, e, o",
    pattern: "aiueo foundation",
    coverage: ["あ い う え お", "Mouth shape control", "Steady rhythm", "Mini vowel words"],
    outcome: "Learner can repeat the full vowel line with more even rhythm and mouth shape control.",
    replyPrompt: "Repeat aiueo clearly and evenly once from start to finish.",
    rewardBadge: "Vowel Master",
    rewardXp: 15,
    acceptableResponses: ["a i u e o", "aiueo", "あいうえお"],
    modelPrompt: "Model the vowels slowly, then naturally, so the learner hears openness and timing instead of English letter names.",
    guidedPrompt: "Ask for the full vowel line, then isolate the hardest vowel once for a cleaner retry.",
    checkpoint: "Finish when the learner can say aiueo in one steady line.",
  }),
  createJapaneseSeed({
    id: "n5-sound-patterns",
    title: "Japanese sound patterns",
    missionTitle: "Mission 4: Unlock the sound rows",
    objective: "Teach the consonant-plus-vowel rhythm that powers most beginner Japanese sounds and reading confidence.",
    storyHook: "Japanese stops feeling random once you hear the rows. This mission reveals the rhythm pattern behind ka, sa, ta, and the rest.",
    checkpointLabel: "Sound row check",
    mode: "speaking",
    demoPhrase: "ka ki ku ke ko, sa shi su se so",
    pattern: "CV sound rows",
    coverage: ["Consonant + vowel pattern", "a-row", "ka-row", "sa-row", "ta-row", "ya/yu/yo", "wa/wo/n"],
    outcome: "Learner can hear and say the logic of Japanese sound rows instead of memorizing isolated syllables.",
    replyPrompt: "Say the ka-row and the sa-row clearly in order.",
    rewardBadge: "Sound Row Starter",
    rewardXp: 15,
    acceptableResponses: ["ka ki ku ke ko", "sa shi su se so", "かきくけこ", "さしすせそ"],
    modelPrompt: "Model two sound rows like a rhythm drill so the learner feels the structure under Japanese.",
    guidedPrompt: "Ask the learner for one full row, then switch rows to test active recall by voice.",
    checkpoint: "The learner clears both sound rows without collapsing into English-style stress.",
  }),
  createJapaneseSeed({
    id: "n5-hiragana-basics",
    title: "Hiragana basics",
    missionTitle: "Mission 5: Read your first real hiragana",
    objective: "Unlock the 46 core hiragana through sound-first practice so reading feels alive instead of textbook-heavy.",
    storyHook: "You see すし and ねこ for the first time and realize Japanese is becoming readable. This mission opens the native script properly.",
    checkpointLabel: "Hiragana reading mission",
    mode: "listening",
    demoPhrase: "すし, ねこ, にほん",
    pattern: "basic hiragana reading",
    coverage: ["46 hiragana", "Row-by-row reading", "Starter hiragana words", "Full reading practice", "Writing awareness"],
    outcome: "Learner can recognize and say their first real hiragana words with confidence.",
    replyPrompt: "Read sushi, neko, and nihon aloud once in Japanese rhythm.",
    rewardBadge: "Hiragana Hero",
    rewardXp: 20,
    acceptableResponses: ["sushi", "neko", "nihon", "すし", "ねこ", "にほん"],
    modelPrompt: "Model small hiragana words that feel rewarding and instantly useful for a first reading win.",
    guidedPrompt: "Ask the learner to read three friendly words, then repeat the hardest one with smoother flow.",
    checkpoint: "Mark success when the learner reads three hiragana words aloud without freezing.",
  }),
  createJapaneseSeed({
    id: "n5-hiragana-special",
    title: "Hiragana special sounds",
    missionTitle: "Mission 6: Master the tricky hiragana sounds",
    objective: "Master voiced sounds, small ya-yu-yo combinations, pauses, and long vowels so beginner speech becomes more realistic.",
    storyHook: "Now the script starts behaving like real Japanese. Small marks and small letters change meaning, rhythm, and confidence.",
    checkpointLabel: "Special sounds check",
    mode: "repeat",
    demoPhrase: "gakkou, kyou, byouin",
    pattern: "dakuon, yoon, sokuon, and long vowels",
    coverage: ["Dakuon", "Handakuon", "Yoon", "Sokuon", "Long vowels", "Meaning-changing sound contrast"],
    outcome: "Learner can hear why small sound changes matter and repeat them more accurately.",
    replyPrompt: "Repeat gakkou, kyou, and byouin with clear timing.",
    rewardBadge: "Special Sounds Badge",
    rewardXp: 20,
    acceptableResponses: ["gakkou", "kyou", "byouin", "がっこう", "きょう", "びょういん"],
    modelPrompt: "Model words that showcase pauses and glide sounds so the learner hears real contrast.",
    guidedPrompt: "Ask the learner to repeat one pause word and one glide word, then compare the rhythm.",
    checkpoint: "The learner demonstrates one clean pause sound and one clean yoon sound.",
  }),
  createJapaneseSeed({
    id: "n5-katakana-basics",
    title: "Katakana basics",
    missionTitle: "Mission 7: Read Japan's imported words",
    objective: "Teach foreign and modern words through katakana so the learner can hear Japanese in travel, food, and daily signs.",
    storyHook: "At the airport, cafe, and station, katakana is everywhere. This mission turns those modern words into something you can actually say.",
    checkpointLabel: "Katakana basics check",
    mode: "listening",
    demoPhrase: "ホテル, コーヒー, タクシー",
    pattern: "starter katakana reading",
    coverage: ["46 katakana", "Loanword rhythm", "Travel words", "Food and cafe words", "Full reading practice"],
    outcome: "Learner can read and repeat beginner katakana loanwords with better listening confidence.",
    replyPrompt: "Read hotel, coffee, and taxi in Japanese aloud.",
    rewardBadge: "Katakana Explorer",
    rewardXp: 20,
    acceptableResponses: ["hoteru", "koohii", "takushii", "ホテル", "コーヒー", "タクシー"],
    modelPrompt: "Model familiar katakana words so the learner hears how imported words reshape inside Japanese rhythm.",
    guidedPrompt: "Ask the learner to repeat one travel word and one drink word, then answer which one they heard.",
    checkpoint: "The learner reads three useful katakana words with calmer timing.",
  }),
  createJapaneseSeed({
    id: "n5-katakana-special",
    title: "Katakana special sounds",
    missionTitle: "Mission 8: Handle modern Japanese sound twists",
    objective: "Expand katakana with voiced, combined, and long sounds so imported vocabulary feels much less intimidating.",
    storyHook: "Baggu, juusu, and chokoreeto do not sound like English anymore. This mission trains your ear for Japan's modern pronunciation patterns.",
    checkpointLabel: "Katakana special sounds check",
    mode: "repeat",
    demoPhrase: "baggu, juusu, chokoreeto",
    pattern: "katakana combinations and long vowels",
    coverage: ["Voiced katakana", "Long vowels", "Combined sounds", "Double consonants", "Modern spoken vocabulary"],
    outcome: "Learner can repeat modern Japanese words with better control of extended and doubled sounds.",
    replyPrompt: "Repeat baggu, juusu, and chokoreeto once clearly.",
    rewardBadge: "Katakana Sound Pro",
    rewardXp: 20,
    acceptableResponses: ["baggu", "juusu", "chokoreeto", "バッグ", "ジュース", "チョコレート"],
    modelPrompt: "Model three common katakana words with clear long vowels and held consonants.",
    guidedPrompt: "Ask the learner for one word at a time, then retry the most difficult long vowel once.",
    checkpoint: "The learner can hold one long vowel and one doubled consonant correctly.",
  }),
  createJapaneseSeed({
    id: "n5-numbers-0-100",
    title: "Numbers 0-100",
    missionTitle: "Mission 9: Count yen and everyday numbers",
    objective: "Give the learner practical control over counting so numbers stop feeling like random sounds.",
    storyHook: "You start seeing prices, floor numbers, and seat numbers everywhere. This mission makes counting useful from day one.",
    checkpointLabel: "Number ladder check",
    mode: "speaking",
    demoPhrase: "ichi, ni, san, yon, go",
    pattern: "counting and tens building",
    coverage: ["0-100", "11-20", "Tens pattern", "Combining numbers", "Fast spoken counting"],
    outcome: "Learner can count, combine tens, and answer small number prompts aloud.",
    replyPrompt: "Count one to five, then say twenty-one and ninety-nine.",
    rewardBadge: "Number Ninja",
    rewardXp: 15,
    acceptableResponses: ["ichi ni san yon go", "nijuuichi", "kyuujuukyuu", "いち", "にじゅういち", "きゅうじゅうきゅう"],
    modelPrompt: "Model small counting bursts first, then show how Japanese stacks numbers into bigger answers.",
    guidedPrompt: "Ask for a small count, then a bigger number so the learner shifts from repetition into construction.",
    checkpoint: "The learner answers one basic count and one combined number correctly.",
  }),
  createJapaneseSeed({
    id: "n5-money-time-dates",
    title: "Money, time, and dates",
    missionTitle: "Mission 10: Use numbers in real life",
    objective: "Make beginner Japanese feel useful immediately through prices, age, time, and weekdays.",
    storyHook: "Buying something, answering your age, and telling time are the first moments where Japanese becomes practical. This mission prepares all three.",
    checkpointLabel: "Real-life numbers check",
    mode: "roleplay",
    demoPhrase: "これは いくらですか。 ろくじです。",
    pattern: "money, age, time, and weekday answers",
    coverage: ["Yen prices", "How old are you?", "Clock time", "Weekdays", "Practical number replies"],
    outcome: "Learner can ask a simple price and answer a basic time question in spoken Japanese.",
    replyPrompt: "Ask how much it is, then say six o'clock.",
    rewardBadge: "Real-Life Numbers",
    rewardXp: 15,
    acceptableResponses: ["ikura desu ka", "rokuji", "これは いくらですか", "ろくじです"],
    modelPrompt: "Model a tiny shopping and time exchange so numbers feel tied to real life, not drill-only memory.",
    guidedPrompt: "Run one price question and one time response, then retry the harder one once for clarity.",
    checkpoint: "The learner handles one practical money or time answer without getting lost.",
  }),
];
