import { type ExamQuestion } from "@/lib/course-types";

function question(
  id: string,
  sectionId: string,
  skillFocus: string,
  prompt: string,
  questionType: string,
  correctAnswer: string,
  explanation: string,
  choices: string[] = [],
): ExamQuestion {
  return {
    choices,
    correctAnswer,
    explanation,
    id,
    prompt,
    questionType,
    sectionId,
    skillFocus,
  };
}

export const japaneseQuestionBankA = [
  question(
    "n5-sound-1",
    "sounds-romaji",
    "Vowel order",
    "Say the five Japanese vowels in the correct order.",
    "spoken response",
    "a, i, u, e, o",
    "The basic vowel line is always spoken in this order and becomes the foundation for later sound rows.",
  ),
  question(
    "n5-sound-2",
    "sounds-romaji",
    "Consonant row rhythm",
    "Which row matches the ka-line?",
    "multiple choice",
    "ka, ki, ku, ke, ko",
    "The ka-row keeps the same vowel order while the initial consonant changes to k.",
    ["sa, shi, su, se, so", "ka, ki, ku, ke, ko", "ta, chi, tsu, te, to"],
  ),
  question(
    "n5-sound-3",
    "sounds-romaji",
    "Long vowel awareness",
    "In a speaking drill, what should you do with a long vowel?",
    "short answer",
    "Hold it a little longer without breaking the rhythm.",
    "Long vowels change meaning, so the learner should lengthen them smoothly rather than clipping them short.",
  ),
  question(
    "n5-hiragana-1",
    "hiragana",
    "Basic script recall",
    "Read this hiragana aloud: あ",
    "spoken response",
    "a",
    "あ is the first hiragana and represents the vowel sound a.",
  ),
  question(
    "n5-hiragana-2",
    "hiragana",
    "Word reading",
    "What is the reading of さくら?",
    "short answer",
    "sakura",
    "The learner should connect individual hiragana sounds into one natural word rather than reading character by character.",
  ),
  question(
    "n5-hiragana-3",
    "hiragana",
    "Character recognition",
    "Which hiragana is read as 'ne'?",
    "multiple choice",
    "ね",
    "Recognizing common kana quickly is essential before moving into phrases and roleplay.",
    ["れ", "ぬ", "ね"],
  ),
  question(
    "n5-katakana-1",
    "katakana",
    "Loanword reading",
    "Read this katakana word aloud: コーヒー",
    "spoken response",
    "koohii",
    "The long vowels matter here. The learner should stretch the middle and final vowels naturally.",
  ),
  question(
    "n5-katakana-2",
    "katakana",
    "Travel word recognition",
    "Which word means 'taxi'?",
    "multiple choice",
    "タクシー",
    "Katakana often appears in travel and daily borrowed words, so this is a high-value recognition item.",
    ["タクシー", "ホテル", "バス"],
  ),
  question(
    "n5-katakana-3",
    "katakana",
    "Cafe vocabulary",
    "Say the katakana word for 'juice': ジュース",
    "spoken response",
    "juusu",
    "This checks comfort with long vowel timing inside a common cafe word.",
  ),
  question(
    "n5-special-1",
    "special-kana",
    "Yoon combination",
    "How do you read きゃ?",
    "short answer",
    "kya",
    "The small ゃ combines with the previous kana into one blended syllable.",
  ),
  question(
    "n5-special-2",
    "special-kana",
    "Small tsu timing",
    "What does the small っ usually signal in speech?",
    "short answer",
    "A brief pause or doubled consonant.",
    "The learner should feel a short stop before the next consonant rather than adding an extra vowel.",
  ),
  question(
    "n5-special-3",
    "special-kana",
    "Voiced contrast",
    "Which sound pair shows an unvoiced to voiced shift?",
    "multiple choice",
    "ka -> ga",
    "Dakuon adds voicing, so the learner hears the sound become heavier at the start.",
    ["ha -> pa", "ka -> ga", "ya -> wa"],
  ),
  question(
    "n5-numbers-1",
    "numbers",
    "Practical counting",
    "Say 47 in Japanese.",
    "spoken response",
    "yon juu nana",
    "This checks the learner's ability to combine tens and units clearly in live speech.",
  ),
  question(
    "n5-numbers-2",
    "numbers",
    "Time telling",
    "How do you say 7 o'clock?",
    "short answer",
    "shichi ji",
    "Hour expressions are core N5 survival Japanese and should come out quickly without translation delay.",
  ),
] as const;
