import { type SupplementalVocabularyBank } from "@/lib/japanese-vocab-supplement";

export const japaneseVocabularyExtraE: SupplementalVocabularyBank = {
  nature: [
    ["き", "ki", "tree"],
    ["もり", "mori", "forest"],
    ["はな", "hana", "flower"],
    ["くさ", "kusa", "grass"],
    ["かわ", "kawa", "river"],
    ["いし", "ishi", "stone"],
    ["つき", "tsuki", "moon"],
    ["たいよう", "taiyou", "sun"],
    ["ほし", "hoshi", "star"],
    ["そら", "sora", "sky"],
    ["うみ", "umi", "sea"],
    ["やま", "yama", "mountain"],
    ["どうぶつ", "doubutsu", "animal"],
    ["とり", "tori", "bird"],
    ["いぬ", "inu", "dog"],
    ["ねこ", "neko", "cat"],
    ["さかな", "sakana", "fish"],
    ["むし", "mushi", "insect"],
  ],
  "body-parts": [
    ["あたま", "atama", "head"],
    ["かお", "kao", "face"],
    ["め", "me", "eye"],
    ["みみ", "mimi", "ear"],
    ["くち", "kuchi", "mouth"],
    ["は", "ha", "tooth"],
    ["て", "te", "hand"],
    ["あし", "ashi", "leg or foot"],
    ["うで", "ude", "arm"],
    ["ゆび", "yubi", "finger"],
    ["おなか", "onaka", "stomach"],
    ["せなか", "senaka", "back"],
    ["のど", "nodo", "throat"],
    ["はな", "hana", "nose"],
    ["からだ", "karada", "body"],
    ["かみ", "kami", "hair"],
    ["こころ", "kokoro", "heart or mind"],
    ["びょうき", "byouki", "illness"],
  ],
  colors: [
    ["あか", "aka", "red"],
    ["あお", "ao", "blue"],
    ["きいろ", "kiiro", "yellow"],
    ["みどり", "midori", "green"],
    ["しろ", "shiro", "white"],
    ["くろ", "kuro", "black"],
    ["ちゃいろ", "chairo", "brown"],
    ["むらさき", "murasaki", "purple"],
    ["ピンク", "pinku", "pink"],
    ["オレンジ", "orenji", "orange"],
    ["はいいろ", "haiiro", "gray"],
    ["こんいろ", "koniro", "navy blue"],
    ["きんいろ", "kiniro", "gold color"],
    ["ぎんいろ", "giniro", "silver color"],
    ["いろ", "iro", "color"],
    ["カラフル", "karafuru", "colorful"],
    ["うすい", "usui", "light or pale"],
    ["こい", "koi", "dark or deep"],
  ],
  "basic-verbs": [
    ["あります", "arimasu", "to exist for things"],
    ["います", "imasu", "to exist for living things"],
    ["おきます", "okimasu", "to wake up"],
    ["ねます", "nemasu", "to sleep"],
    ["はじまります", "hajimarimasu", "to begin"],
    ["おわります", "owarimasu", "to end"],
    ["まちます", "machimasu", "to wait"],
    ["とります", "torimasu", "to take"],
    ["もちます", "mochimasu", "to hold"],
    ["あけます", "akemasu", "to open"],
    ["しめます", "shimemasu", "to close"],
    ["すわります", "suwarimasu", "to sit"],
    ["たちます", "tachimasu", "to stand up"],
    ["はいります", "hairimasu", "to enter"],
    ["でます", "demasu", "to leave"],
    ["ならいます", "naraimasu", "to learn"],
    ["おしえます", "oshiemasu", "to teach"],
    ["ききます", "kikimasu", "to listen or ask"],
    ["わかります", "wakarimasu", "to understand"],
    ["つかいます", "tsukaimasu", "to use"],
  ],
  "basic-adjectives": [
    ["たのしい", "tanoshii", "fun"],
    ["かなしい", "kanashii", "sad"],
    ["いそがしい", "isogashii", "busy"],
    ["やさしい", "yasashii", "kind or easy"],
    ["むずかしい", "muzukashii", "difficult"],
    ["うれしい", "ureshii", "happy"],
    ["こわい", "kowai", "scary"],
    ["ねむい", "nemui", "sleepy"],
    ["いたい", "itai", "painful"],
    ["あかるい", "akarui", "bright"],
    ["くらい", "kurai", "dark"],
    ["しずかな", "shizuka na", "quiet"],
    ["にぎやかな", "nigiyaka na", "lively"],
    ["べんりな", "benri na", "convenient"],
    ["ふべんな", "fuben na", "inconvenient"],
    ["げんきな", "genki na", "healthy or lively"],
    ["ひまな", "hima na", "free, not busy"],
    ["だいじな", "daiji na", "important"],
  ],
};
