import { type SupplementalVocabularyBank } from "@/lib/japanese-vocab-supplement";

export const japaneseVocabularyExtraD: SupplementalVocabularyBank = {
  buildings: [
    ["ぎんこう", "ginkou", "bank"],
    ["ゆうびんきょく", "yuubinkyoku", "post office"],
    ["デパート", "depaato", "department store"],
    ["スーパー", "suupaa", "supermarket"],
    ["コンビニ", "konbini", "convenience store"],
    ["くうこう", "kuukou", "airport"],
    ["こうばん", "kouban", "police box"],
    ["びょういんのうけつけ", "byouin no uketsuke", "hospital reception"],
    ["えいがかん", "eigakan", "movie theater"],
    ["びじゅつかん", "bijutsukan", "art museum"],
    ["はくぶつかん", "hakubutsukan", "museum"],
    ["だいがく", "daigaku", "university"],
    ["こうこう", "koukou", "high school"],
    ["いんしょくてん", "inshokuten", "eating place"],
    ["じむしょ", "jimusho", "office"],
    ["りょかん", "ryokan", "Japanese inn"],
    ["マンション", "manshon", "apartment building"],
    ["たてもの", "tatemono", "building"],
  ],
  transportation: [
    ["でんしゃ", "densha", "train"],
    ["ひこうき", "hikouki", "airplane"],
    ["じてんしゃ", "jitensha", "bicycle"],
    ["ふね", "fune", "boat"],
    ["しんかんせん", "shinkansen", "bullet train"],
    ["ちかてつ", "chikatetsu", "subway"],
    ["あるきます", "arukimasu", "to walk"],
    ["とまります", "tomarimasu", "to stop"],
    ["のります", "norimasu", "to ride"],
    ["おります", "orimasu", "to get off"],
    ["しゅっぱつ", "shuppatsu", "departure"],
    ["とうちゃく", "touchaku", "arrival"],
    ["きっぷ", "kippu", "ticket"],
    ["ていきけん", "teikiken", "commuter pass"],
    ["うんてん", "unten", "driving"],
    ["バスてい", "basutei", "bus stop"],
    ["ホーム", "hoomu", "platform"],
    ["ターミナル", "taaminaru", "terminal"],
  ],
  "everyday-objects": [
    ["けいたい", "keitai", "mobile phone"],
    ["スマホ", "sumaho", "smartphone"],
    ["さいふ", "saifu", "wallet"],
    ["かぎ", "kagi", "key"],
    ["めがね", "megane", "glasses"],
    ["とけい", "tokei", "watch or clock"],
    ["テレビ", "terebi", "television"],
    ["れいぞうこ", "reizouko", "refrigerator"],
    ["つくえのうえ", "tsukue no ue", "on the desk"],
    ["かみ", "kami", "paper"],
    ["えんぴつ", "enpitsu", "pencil"],
    ["けしごむ", "keshigomu", "eraser"],
    ["ハサミ", "hasami", "scissors"],
    ["てがみ", "tegami", "letter"],
    ["しゃしん", "shashin", "photo"],
    ["でんち", "denchi", "battery"],
    ["ふくろ", "fukuro", "bag or sack"],
    ["にもつ", "nimotsu", "baggage"],
  ],
  clothing: [
    ["くつ", "kutsu", "shoes"],
    ["くつした", "kutsushita", "socks"],
    ["ぼうし", "boushi", "hat"],
    ["コート", "kooto", "coat"],
    ["ジャケット", "jaketto", "jacket"],
    ["ズボン", "zubon", "trousers"],
    ["スカート", "sukaato", "skirt"],
    ["セーター", "seetaa", "sweater"],
    ["ドレス", "doresu", "dress"],
    ["てぶくろ", "tebukuro", "gloves"],
    ["マフラー", "mafuraa", "scarf"],
    ["ベルト", "beruto", "belt"],
    ["パジャマ", "pajama", "pajamas"],
    ["サイズ", "saizu", "size"],
    ["きがえます", "kigaemasu", "to change clothes"],
    ["きます", "kimasu", "to wear"],
    ["はきます", "hakimasu", "to put on lower-body clothing"],
    ["ぬぎます", "nugimasu", "to take off clothing"],
  ],
  weather: [
    ["てんき", "tenki", "weather"],
    ["いいてんき", "ii tenki", "good weather"],
    ["わるいてんき", "warui tenki", "bad weather"],
    ["かぜ", "kaze", "wind"],
    ["たいふう", "taifuu", "typhoon"],
    ["あたたかい", "atatakai", "warm"],
    ["すずしい", "suzushii", "cool"],
    ["つめたい", "tsumetai", "cold to the touch"],
    ["むしあつい", "mushiatsui", "humid and hot"],
    ["くも", "kumo", "cloud"],
    ["はれる", "hareru", "to clear up"],
    ["ふります", "furimasu", "to fall from the sky"],
    ["ゆきがふります", "yuki ga furimasu", "snow falls"],
    ["あめがふります", "ame ga furimasu", "rain falls"],
    ["そら", "sora", "sky"],
    ["にじ", "niji", "rainbow"],
    ["きおん", "kion", "temperature"],
    ["よほう", "yohou", "forecast"],
  ],
};
