import { type SupplementalVocabularyBank } from "@/lib/japanese-vocab-supplement";

export const japaneseVocabularyExtraB: SupplementalVocabularyBank = {
  numbers: [
    ["れい", "rei", "zero"],
    ["にひゃく", "nihyaku", "two hundred"],
    ["さんびゃく", "sanbyaku", "three hundred"],
    ["ろっぴゃく", "roppyaku", "six hundred"],
    ["はっぴゃく", "happyaku", "eight hundred"],
    ["せん", "sen", "one thousand"],
    ["にせん", "nisen", "two thousand"],
    ["さんぜん", "sanzen", "three thousand"],
    ["よんせん", "yonsen", "four thousand"],
    ["ごせん", "gosen", "five thousand"],
    ["ろくせん", "rokusen", "six thousand"],
    ["ななせん", "nanasen", "seven thousand"],
    ["はっせん", "hassen", "eight thousand"],
    ["きゅうせん", "kyuusen", "nine thousand"],
    ["いちまん", "ichiman", "ten thousand"],
    ["なんばん", "nanban", "what number"],
    ["なんこ", "nanko", "how many things"],
    ["たくさん", "takusan", "many"],
  ],
  money: [
    ["おかね", "okane", "money"],
    ["かいけい", "kaikei", "bill or check"],
    ["はらいます", "haraimasu", "to pay"],
    ["げんきん", "genkin", "cash"],
    ["カード", "kaado", "card"],
    ["りょうしゅうしょ", "ryoushuusho", "receipt"],
    ["ねだん", "nedan", "price"],
    ["やすく", "yasuku", "cheaply"],
    ["たかく", "takaku", "expensively"],
    ["セール", "seeru", "sale"],
    ["はんがく", "hangaku", "half price"],
    ["むりょう", "muryou", "free of charge"],
    ["しょうひぜい", "shouhizei", "consumption tax"],
    ["おさつ", "osatsu", "bank note"],
    ["こぜに", "kozeni", "small coins"],
    ["いちまんえん", "ichiman en", "ten thousand yen"],
    ["さんびゃくえん", "sanbyaku en", "three hundred yen"],
    ["ごせんえん", "gosen en", "five thousand yen"],
  ],
  family: [
    ["りょうしん", "ryoushin", "parents"],
    ["ふうふ", "fuufu", "married couple"],
    ["つま", "tsuma", "my wife"],
    ["おくさん", "okusan", "someone's wife"],
    ["おっと", "otto", "my husband"],
    ["ごしゅじん", "goshujin", "someone's husband"],
    ["むすこ", "musuko", "son"],
    ["むすめ", "musume", "daughter"],
    ["おじいさん", "ojiisan", "grandfather"],
    ["おばあさん", "obaasan", "grandmother"],
    ["まご", "mago", "grandchild"],
    ["おじ", "oji", "uncle"],
    ["おば", "oba", "aunt"],
    ["いとこ", "itoko", "cousin"],
    ["きょうだい", "kyoudai", "siblings"],
    ["ひとりっこ", "hitorikko", "only child"],
    ["かぞくしゃしん", "kazoku shashin", "family photo"],
    ["いえのひと", "ie no hito", "family member"],
  ],
  people: [
    ["みんな", "minna", "everyone"],
    ["だれか", "dareka", "someone"],
    ["じぶん", "jibun", "oneself"],
    ["こいびと", "koibito", "boyfriend or girlfriend"],
    ["おとな", "otona", "adult"],
    ["わかもの", "wakamono", "young person"],
    ["あかちゃん", "akachan", "baby"],
    ["おきゃくさん", "okyakusan", "customer or guest"],
    ["てんいん", "tenin", "store clerk"],
    ["せいと", "seito", "pupil"],
    ["どうりょう", "douryou", "coworker"],
    ["しゃいん", "shain", "employee"],
    ["しんせつなひと", "shinsetsu na hito", "kind person"],
    ["ゆうめいじん", "yuumeijin", "famous person"],
    ["にほんじん", "nihonjin", "Japanese person"],
    ["がいこくじん", "gaikokujin", "foreigner"],
    ["せんぱい", "senpai", "senior"],
    ["こうはい", "kouhai", "junior"],
  ],
  jobs: [
    ["エンジニア", "enjinia", "engineer"],
    ["いしゃ", "isha", "doctor"],
    ["かんごし", "kangoshi", "nurse"],
    ["てんいん", "tenin", "shop clerk"],
    ["うんてんしゅ", "untenshu", "driver"],
    ["けいさつかん", "keisatsukan", "police officer"],
    ["ぎんこういん", "ginkouin", "bank employee"],
    ["かいしゃいん", "kaishain", "company employee"],
    ["シェフ", "shefu", "chef"],
    ["ウェイター", "weitaa", "waiter"],
    ["アルバイト", "arubaito", "part-time worker"],
    ["がくしゃ", "gakusha", "scholar"],
    ["だいがくせい", "daigakusei", "university student"],
    ["こうこうせい", "koukousei", "high school student"],
    ["しょうがくせい", "shougakusei", "elementary school student"],
    ["かしゅ", "kashu", "singer"],
    ["えんぎしゃ", "engisha", "actor"],
    ["りょうりにん", "ryourinin", "cook"],
  ],
};
