import { type SupplementalVocabularyBank } from "@/lib/japanese-vocab-supplement";

export const japaneseVocabularyExtraA: SupplementalVocabularyBank = {
  greetings: [
    ["はじめまして", "hajimemashite", "nice to meet you"],
    ["おげんきですか", "ogenki desu ka", "how are you"],
    ["げんきです", "genki desu", "I am fine"],
    ["いってきます", "ittekimasu", "I am leaving and will come back"],
    ["いってらっしゃい", "itterasshai", "take care, see you later"],
    ["ただいま", "tadaima", "I am home"],
    ["おかえりなさい", "okaerinasai", "welcome back"],
    ["しつれいします", "shitsurei shimasu", "excuse me"],
    ["おめでとうございます", "omedetou gozaimasu", "congratulations"],
    ["あけましておめでとうございます", "akemashite omedetou gozaimasu", "happy new year"],
    ["おひさしぶりです", "ohisashiburi desu", "long time no see"],
    ["またあした", "mata ashita", "see you tomorrow"],
    ["またこんど", "mata kondo", "see you next time"],
    ["きをつけて", "ki o tsukete", "take care"],
    ["いただきます", "itadakimasu", "let's eat"],
    ["ごちそうさまでした", "gochisousama deshita", "thank you for the meal"],
    ["もしもし", "moshi moshi", "hello on the phone"],
    ["ようこそ", "youkoso", "welcome"],
    ["おさきにしつれいします", "osaki ni shitsurei shimasu", "excuse me for leaving first"],
    ["おつかれさまです", "otsukaresama desu", "thank you for your work"],
  ],
  "classroom-japanese": [
    ["しつもんがあります", "shitsumon ga arimasu", "I have a question"],
    ["もういちど", "mou ichido", "one more time"],
    ["ゆっくり", "yukkuri", "slowly"],
    ["だいじょうぶです", "daijoubu desu", "it is okay"],
    ["ノート", "nooto", "notebook"],
    ["れい", "rei", "example"],
    ["こたえ", "kotae", "answer"],
    ["もんだい", "mondai", "problem or question"],
    ["テスト", "tesuto", "test"],
    ["れんしゅう", "renshuu", "practice"],
    ["べんきょう", "benkyou", "study"],
    ["しゅくだい", "shukudai", "homework"],
    ["きょうかしょ", "kyoukasho", "textbook"],
    ["じしょ", "jisho", "dictionary"],
    ["おしえてください", "oshiete kudasai", "please teach me"],
    ["つぎ", "tsugi", "next"],
    ["さいしょ", "saisho", "first"],
    ["さいご", "saigo", "last"],
    ["ただしい", "tadashii", "correct"],
    ["まちがい", "machigai", "mistake"],
  ],
  "time-expressions": [
    ["けさ", "kesa", "this morning"],
    ["こんや", "konya", "tonight"],
    ["こんばん", "konban", "this evening"],
    ["こんしゅう", "konshuu", "this week"],
    ["らいしゅう", "raishuu", "next week"],
    ["せんしゅう", "senshuu", "last week"],
    ["こんげつ", "kongetsu", "this month"],
    ["らいげつ", "raigetsu", "next month"],
    ["せんげつ", "sengetsu", "last month"],
    ["ことし", "kotoshi", "this year"],
    ["らいねん", "rainen", "next year"],
    ["きょねん", "kyonen", "last year"],
    ["まいあさ", "maiasa", "every morning"],
    ["まいばん", "maiban", "every night"],
    ["いつも", "itsumo", "always"],
    ["ときどき", "tokidoki", "sometimes"],
    ["すぐ", "sugu", "right away"],
    ["さっき", "sakki", "a little while ago"],
    ["このあと", "kono ato", "after this"],
    ["そのあと", "sono ato", "after that"],
  ],
  weekdays: [
    ["しゅうまつ", "shuumatsu", "weekend"],
    ["へいじつ", "heijitsu", "weekday"],
    ["げつ", "getsu", "Monday short form"],
    ["か", "ka", "Tuesday short form"],
    ["すい", "sui", "Wednesday short form"],
    ["もく", "moku", "Thursday short form"],
    ["きん", "kin", "Friday short form"],
    ["ど", "do", "Saturday short form"],
    ["にち", "nichi", "Sunday short form"],
    ["まいしゅう", "maishuu", "every week"],
    ["こんどのげつようび", "kondo no getsuyoubi", "this coming Monday"],
    ["らいしゅうのかようび", "raishuu no kayoubi", "next Tuesday"],
    ["にちようのあさ", "nichiyou no asa", "Sunday morning"],
    ["きんようのよる", "kinyou no yoru", "Friday night"],
    ["どようびのごご", "doyoubi no gogo", "Saturday afternoon"],
    ["やすみのひ", "yasumi no hi", "day off"],
    ["しごとのひ", "shigoto no hi", "work day"],
    ["がっこうのひ", "gakkou no hi", "school day"],
  ],
  "months-dates": [
    ["にがつ", "nigatsu", "February"],
    ["さんがつ", "sangatsu", "March"],
    ["ごがつ", "gogatsu", "May"],
    ["ろくがつ", "rokugatsu", "June"],
    ["はちがつ", "hachigatsu", "August"],
    ["くがつ", "kugatsu", "September"],
    ["じゅうがつ", "juugatsu", "October"],
    ["じゅういちがつ", "juuichigatsu", "November"],
    ["ふつか", "futsuka", "second day"],
    ["みっか", "mikka", "third day"],
    ["よっか", "yokka", "fourth day"],
    ["いつか", "itsuka", "fifth day"],
    ["むいか", "muika", "sixth day"],
    ["なのか", "nanoka", "seventh day"],
    ["ようか", "youka", "eighth day"],
    ["ここのか", "kokonoka", "ninth day"],
    ["とおか", "tooka", "tenth day"],
    ["はつか", "hatsuka", "twentieth day"],
    ["にじゅうよっか", "nijuuyokka", "twenty fourth day"],
    ["さんじゅうにち", "sanjuunichi", "thirtieth day"],
  ],
};
